//! End-to-end ICC colour-management integration tests (ICC-6).
//!
//! Decodes the committed profiled test images through the full `lumen_image::decode`
//! pipeline (format decode → `color_manage_in_place` → sRGB) and asserts the
//! recovered sRGB swatches. These guard the whole PNG-iCCP → matrix-shaper and
//! JPEG-APP2 → CMYK-`A2B0` paths against regression without any GPU/Edge dependency.
//!
//! The images are generated by `graphic_tests/gen_icc_images.py`, whose maths
//! mirrors `lumen_core::icc` byte-for-byte; see that script for how the pixels
//! were chosen (RGB: swatches round-tripped through Display-P3; CMYK: ink tuples
//! placed on CLUT grid nodes).

use lumen_image::{Image, PixelFormat};
use std::path::PathBuf;

/// Path to a committed sample image, resolved from the crate manifest dir.
fn sample(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../../samples/images")
        .join(name)
}

/// Returns the RGB of the pixel at the centre of swatch column `i` of `n`,
/// handling both compact `Rgb8` (stride 3) and `Rgba8` (stride 4) layouts.
fn swatch_rgb(img: &Image, i: usize, n: usize) -> (i32, i32, i32) {
    let stride = match img.format {
        PixelFormat::Rgb8 => 3,
        PixelFormat::Rgba8 => 4,
        other => panic!("unexpected decoded format {other:?}"),
    };
    let w = img.width as usize;
    let h = img.height as usize;
    let col_w = w / n;
    let x = i * col_w + col_w / 2;
    let y = h / 2;
    let idx = (y * w + x) * stride;
    (
        i32::from(img.data[idx]),
        i32::from(img.data[idx + 1]),
        i32::from(img.data[idx + 2]),
    )
}

fn assert_close(got: (i32, i32, i32), want: (i32, i32, i32), tol: i32, label: &str) {
    let d = (got.0 - want.0).abs().max((got.1 - want.1).abs()).max((got.2 - want.2).abs());
    assert!(
        d <= tol,
        "{label}: got {got:?}, want {want:?} (max channel diff {d} > tol {tol})"
    );
}

#[test]
fn display_p3_png_colour_managed_to_srgb() {
    let bytes = std::fs::read(sample("icc_p3.png")).expect("icc_p3.png present");
    let img = lumen_image::decode(&bytes).expect("decode P3 PNG");
    // Targets are the sRGB swatches the generator round-tripped through P3.
    let want = [
        (200, 50, 80),
        (46, 139, 87),
        (65, 105, 225),
        (218, 165, 32),
        (128, 128, 128),
        (240, 240, 240),
    ];
    for (i, w) in want.iter().enumerate() {
        let got = swatch_rgb(&img, i, want.len());
        // tol 3: 1/255 quantisation + Bradford/sRGB rounding.
        assert_close(got, *w, 3, &format!("P3 swatch {i}"));
    }
}

#[test]
fn cmyk_jpeg_colour_managed_via_icc_profile() {
    let bytes = std::fs::read(sample("icc_cmyk.jpg")).expect("icc_cmyk.jpg present");
    let img = lumen_image::decode(&bytes).expect("decode CMYK JPEG");
    // Expected sRGB from the profile's A2B0 CLUT (CMYK ink → PCS → sRGB).
    let want = [
        (255, 255, 255), // paper white
        (0, 255, 255),   // cyan
        (255, 0, 255),   // magenta
        (255, 255, 0),   // yellow
        (0, 0, 0),       // black
        (188, 188, 188), // 50% K grey
    ];
    for (i, w) in want.iter().enumerate() {
        let got = swatch_rgb(&img, i, want.len());
        // Looser tol: JPEG is lossy (even at q=100) + CLUT interpolation.
        assert_close(got, *w, 10, &format!("CMYK swatch {i}"));
    }
}
