#!/usr/bin/env python3
"""WPT-RUN-5 slice 30: what does [BUG-796](../../bugs/BUG-796-FIXED.md) cost the number?

Slice 29 found the defect and bounded its *reach*: `meta.content` answers
`undefined` in our engine (a template getter on the element wrapper shadows the
reflecting one), `testharness.js::test_timeout` picks the file-level ceiling by
`metas[i].content === "long"`, so every one of the corpus's 8 196 `timeout: long`
ids is judged by the 10-second default instead of the 60-second one it declared.
What slice 29 did *not* measure is the price: a test cut off at 10 s is only a
false TIMEOUT if it would have finished inside 60 s, and nothing so far has asked
it.

This audit asks it directly, per test, with an A/B on the same binary:

* **arm A** — the page exactly as the corpus run got it;
* **arm B** — the same page with a shim injected immediately before its
  `testharness.js` include, redefining `content` on every `<meta>` already
  parsed (the shadowing property is `configurable: true`, verified live, so a
  plain `Object.defineProperty` is enough). Nothing else changes: the harness
  still runs at `timeout_multiplier: 1`, so arm B is "BUG-796 fixed", not "more
  time for everyone".

The arms are compared on the same scoring rule the published number uses
(`run_corpus.py::score_reports`: passing subtests over total, or 1.0 for a
subtest-less PASS), so the sample's mean score delta projects straight onto the
population as pass-rate points.

Two things this deliberately does not do. It does not run `wptrunner`: the
corpus run owns the pinned `config.json` ports, and a second runner would either
fight it for them or — worse, see the `StaticHandler` freeze in `CLAUDE.md` —
silently inherit the live run's substituted `--timeout-multiplier`. Pages are
served from a private static server instead, the way `inert_style_audit.py` and
`blank_render_audit.py` do. And it does not touch ids that server cannot serve
faithfully: `.any.*`/`.window.html` (generated by wptserve from a `.js`),
`.sub.` (needs substitution) and anything pulling in `testdriver.js` (needs
wptrunner's message queue) are counted and named, never silently sampled.

Usage (from repo root, venv per tests/wpt/README.md):

    <venv>/python tests/wpt/long_timeout_audit.py --census
    <venv>/python tests/wpt/long_timeout_audit.py --sample 40 --jobs 3 --json OUT
    <venv>/python tests/wpt/long_timeout_audit.py --selftest
"""

import argparse
import asyncio
import collections
import functools
import glob
import http.server
import json
import os
import random
import re
import socket
import subprocess
import sys
import threading
import time

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
WPT_ROOT = os.path.join(REPO_ROOT, "tests", "wpt")
sys.path[:0] = [REPO_ROOT, os.path.join(REPO_ROOT, "tools", "webdriver"),
                os.path.dirname(os.path.abspath(__file__))]

import corpus_stats  # noqa: E402

#: Below this many seconds a TIMEOUT of a `long` id was cut off by the harness's
#: own 10 s default (slice 29 measured the two modes at 10.2 s and 65.0 s; the
#: gap between them is empty, 2 ids of 2 194). Above it the id hit wptrunner's
#: external ceiling, which BUG-796 does not touch.
INTERNAL_CAP_S = 13.0

#: Statuses the score treats as "the harness itself came back".
HARNESS_OK = frozenset({"OK", "PASS"})

#: What `StaticHandler` (wptserve) substitutes into `testharnessreport.js` for a
#: default run — read back off the live server by `route_audit.py` in slice 22,
#: not guessed. Arm B must keep `timeout_multiplier` at 1: the whole point is to
#: change the *declared* ceiling, not to hand every test more wall clock.
REPORT_ARGS = {"output": 0, "timeout_multiplier": 1,
               "explicit_timeout": "false", "debug": "false"}

#: Injected immediately before the page's own `testharness.js` include, so the
#: `Tests` singleton's constructor — which calls `test_timeout()` at parse time —
#: sees a working `content`. Reports how many metas it repaired on
#: `__lumen_repair_applied`, so a run can prove the arm did something rather
#: than assume it.
REPAIR_SHIM = """<script>
(function () {
  var fixed = 0;
  var metas = document.getElementsByTagName('meta');
  for (var i = 0; i < metas.length; i++) {
    var m = metas[i];
    if (m.content !== undefined) { continue; }
    try {
      Object.defineProperty(m, 'content', {
        configurable: true,
        get: (function (el) { return function () { return el.getAttribute('content'); }; })(m)
      });
      fixed++;
    } catch (e) { /* non-configurable: nothing this shim can do */ }
  }
  window.__lumen_repair_applied = fixed;
})();
</script>
"""

_TESTHARNESS_RE = re.compile(
    r"""<script[^>]*\bsrc\s*=\s*["']?[^"'>]*testharness\.js""", re.I)

#: `testharnessreport.js` ships the raw numeric codes, not their names — the
#: naming is `wptrunner`'s (`executors/base.py::TestharnessResultConverter`) and
#: happens on the runner side, which this audit bypasses. Decoding here rather
#: than comparing numbers keeps the buckets readable and, more importantly, keeps
#: `score_of` fed the same status strings the published number is scored from.
HARNESS_CODES = {0: "OK", 1: "ERROR", 2: "TIMEOUT", 3: "PRECONDITION_FAILED"}
SUBTEST_PASS = 0

RESULTS_GLOBAL = "__lumen_wpt_results"
STALE_GLOBAL = "__lumen_wpt_stale"
POLL_INTERVAL_S = 0.1

RESET_EXPRESSION = f"""(() => {{
  window.{RESULTS_GLOBAL} = undefined;
  window.{STALE_GLOBAL} = true;
}})()"""

POLL_EXPRESSION = f"""(() => {{
  if (window.{STALE_GLOBAL} === true) {{ return JSON.stringify({{k: "s"}}); }}
  if (window.{RESULTS_GLOBAL} !== undefined) {{
    return JSON.stringify({{k: "r", v: window.{RESULTS_GLOBAL},
                            fixed: window.__lumen_repair_applied}});
  }}
  return null;
}})()"""


# --------------------------------------------------------------------------- #
# population
# --------------------------------------------------------------------------- #

def long_ids(manifest: dict) -> set:
    """Automatable ids the manifest declares `timeout: long`."""
    out = set()
    for test_type, _category, test_id, extras in corpus_stats.iter_entries(manifest):
        if test_type in corpus_stats.NON_AUTOMATABLE_TYPES:
            continue
        if extras.get("timeout") == "long":
            out.add(test_id)
    return out


def load_verdicts(out_dir: str) -> dict:
    """`{test_id: {"status", "seconds", "subtests", "passed"}}` from the run's reports.

    First writer wins, matching `run_corpus.load_results`: a `--resume` rerun
    appends a second report for the same shard and the earlier one is the run
    the published snapshot was taken from.
    """
    verdicts = {}
    for path in sorted(glob.glob(os.path.join(out_dir, "*.json"))):
        if os.path.basename(path) == "state.json":
            continue
        try:
            with open(path, encoding="utf-8") as fh:
                report = json.load(fh)
        except (OSError, ValueError):
            continue
        for result in report.get("results", []):
            test_id = result.get("test")
            if not test_id or test_id in verdicts:
                continue
            subtests = result.get("subtests") or []
            verdicts[test_id] = {
                "status": result.get("status", ""),
                "seconds": (result.get("duration") or 0) / 1000.0,
                "subtests": len(subtests),
                "passed": sum(1 for s in subtests if s.get("status") == "PASS"),
            }
    return verdicts


def score_of(status: str, subtests: int, passed: int) -> float:
    """The published number's per-id score — `run_corpus.py::score_reports`."""
    if subtests:
        return passed / subtests
    return 1.0 if status == "PASS" else 0.0


def unservable_reason(test_id: str):
    """Why a private static server cannot serve this id faithfully, or None."""
    base = test_id.split("?")[0]
    path = os.path.join(WPT_ROOT, base.lstrip("/"))
    if not os.path.exists(path):
        return "generated by wptserve (.any/.window), no file on disk"
    if ".sub." in base:
        return "needs .sub substitution"
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            source = fh.read()
    except OSError:
        return "unreadable"
    if "testdriver.js" in source:
        return "needs testdriver (wptrunner message queue)"
    return None


#: `<script src=...>` of a test document — used to ask the cheapest possible
#: question about a hanging test before spending a browser on it: does the page
#: even have the helpers it loads? A test whose harness helper is not vendored
#: cannot finish under any ceiling, so it is not evidence about BUG-796 either
#: way, and a sample drawn without separating those two strata measures mostly
#: the vendoring gap.
_HELPER_RE = re.compile(r"""<script[^>]*\bsrc\s*=\s*["']?([^"'>\s]+)""", re.I)
_IFRAME_RE = re.compile(r"<iframe", re.I)
_WORKER_RE = re.compile(r"\bWorker\s*\(|SharedWorker|ServiceWorker")


def structural_blockers(test_id: str) -> set:
    """Reasons this test cannot complete that a longer ceiling would not lift.

    Source scan only, deliberately: it is a filter for choosing what to probe,
    not a verdict. `missing-helper` is the sharp one — the file the page loads
    is not in the checkout, so the harness never gets its `subsetTestByKey` /
    `idl_test` and sits waiting forever. `iframe`/`worker` are softer (the
    engine has neither a nested browsing context nor workers, but a test may
    still complete without ever reaching that part).
    """
    base = test_id.split("?")[0]
    path = os.path.join(WPT_ROOT, base.lstrip("/"))
    try:
        with open(path, encoding="utf-8", errors="replace") as fh:
            source = fh.read()
    except OSError:
        return {"unreadable"}
    tags = set()
    for src in _HELPER_RE.findall(source):
        target = (os.path.join(WPT_ROOT, src.lstrip("/")) if src.startswith("/")
                  else os.path.join(os.path.dirname(path), src))
        if not os.path.exists(target.split("?")[0]):
            tags.add("missing-helper")
    if _IFRAME_RE.search(source):
        tags.add("iframe")
    if _WORKER_RE.search(source):
        tags.add("worker")
    return tags


def missing_helpers(ids) -> collections.Counter:
    """Which unvendored `<script src>` the population is waiting on, by count."""
    counts = collections.Counter()
    for test_id in ids:
        base = test_id.split("?")[0]
        path = os.path.join(WPT_ROOT, base.lstrip("/"))
        try:
            with open(path, encoding="utf-8", errors="replace") as fh:
                source = fh.read()
        except OSError:
            continue
        for src in _HELPER_RE.findall(source):
            target = (os.path.join(WPT_ROOT, src.lstrip("/")) if src.startswith("/")
                      else os.path.join(os.path.dirname(path), src))
            if not os.path.exists(target.split("?")[0]):
                counts[src.split("?")[0]] += 1
    return counts


def census(manifest: dict, verdicts: dict) -> dict:
    """The population this audit is about, before a single browser is started."""
    longs = long_ids(manifest)
    executed = {tid: v for tid, v in verdicts.items() if tid in longs}
    modes = collections.Counter()
    fast, slow = [], []
    for tid, v in executed.items():
        if v["status"] not in ("TIMEOUT", "EXTERNAL-TIMEOUT"):
            continue
        if v["seconds"] < INTERNAL_CAP_S:
            modes["internal 10s cap (BUG-796)"] += 1
            fast.append(tid)
        else:
            modes["external wptrunner cap"] += 1
            slow.append(tid)
    reasons = collections.Counter()
    probeable = []
    for tid in fast:
        reason = unservable_reason(tid)
        if reason:
            reasons[reason] += 1
        else:
            probeable.append(tid)
    strata = collections.Counter()
    unblocked = []
    for tid in probeable:
        tags = structural_blockers(tid)
        if tags:
            for tag in tags:
                strata[tag] += 1
        else:
            strata["no blocker in source"] += 1
            unblocked.append(tid)
    return {
        "long_declared": len(longs),
        "long_executed": len(executed),
        "long_status": dict(collections.Counter(v["status"] for v in executed.values())),
        "timeout_modes": dict(modes),
        "fast": sorted(fast),
        "slow": sorted(slow),
        "probeable": sorted(probeable),
        "unblocked": sorted(unblocked),
        "strata": dict(strata),
        "missing_helpers": dict(missing_helpers(probeable).most_common(10)),
        "unservable": dict(reasons),
    }


# --------------------------------------------------------------------------- #
# private static server
# --------------------------------------------------------------------------- #

class _ArmHandler(http.server.SimpleHTTPRequestHandler):
    """Serves `tests/wpt/`; injects the repair shim when the arm asks for it.

    Two rewrites, both of which a plain file server would get wrong:
    `testharnessreport.js` carries wptserve's four `%%(...)s` placeholders and is
    a syntax error unserved through them, and arm B needs the shim ahead of the
    `testharness.js` include.
    """

    repair = False

    def log_message(self, fmt, *args):  # noqa: D102 - silence per-request logging
        pass

    def do_GET(self):  # noqa: N802 - name fixed by BaseHTTPRequestHandler
        path = self.translate_path(self.path.split("?")[0])
        if not os.path.isfile(path):
            return super().do_GET()
        try:
            with open(path, "rb") as fh:
                raw = fh.read()
        except OSError:
            self.send_error(404)
            return None
        text = raw.decode("utf-8", "replace")
        if path.replace("\\", "/").endswith("/resources/testharnessreport.js"):
            text = text % REPORT_ARGS
        elif self.repair and path.lower().endswith((".html", ".xht", ".xhtml", ".htm")):
            text = inject_shim(text)
        body = text.encode("utf-8")
        self.send_response(200)
        self.send_header("Content-Type", self.guess_type(path))
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)
        return None


def inject_shim(source: str) -> str:
    """Put `REPAIR_SHIM` immediately before the page's `testharness.js` include.

    A page with no such include is returned untouched: it is not a testharness
    test, so there is nothing for the shim to fix in time.
    """
    match = _TESTHARNESS_RE.search(source)
    if not match:
        return source
    return source[:match.start()] + REPAIR_SHIM + source[match.start():]


def start_server(repair: bool) -> tuple:
    """Serve `tests/wpt/` on a free port; returns (server, port)."""
    handler = type("_Arm", (_ArmHandler,), {"repair": repair})
    handler = functools.partial(handler, directory=WPT_ROOT)
    server = http.server.ThreadingHTTPServer(("127.0.0.1", 0), handler)
    server.daemon_threads = True
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server, server.server_address[1]


# --------------------------------------------------------------------------- #
# browser
# --------------------------------------------------------------------------- #

def free_port() -> int:
    """A port nothing holds right now (racy by nature, as everywhere in wpt)."""
    sock = socket.socket()
    try:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]
    finally:
        sock.close()


def launch(binary: str) -> tuple:
    """Start `binary --bidi-port <free>`; returns (proc, port, token)."""
    port = free_port()
    proc = subprocess.Popen([binary, "--bidi-port", str(port)],
                            cwd=REPO_ROOT, stderr=subprocess.PIPE, text=True)
    deadline = time.time() + 60
    while time.time() < deadline:
        if proc.poll() is not None:
            raise RuntimeError(f"lumen exited with {proc.returncode}")
        sock = socket.socket()
        try:
            sock.connect(("127.0.0.1", port))
            break
        except OSError:
            time.sleep(0.05)
        finally:
            sock.close()
    else:
        proc.kill()
        raise TimeoutError("BiDi port never opened")
    token = None
    for _ in range(400):
        line = proc.stderr.readline()
        if not line:
            break
        if line.strip().startswith("[bidi] token: "):
            token = line.strip()[len("[bidi] token: "):]
            break
    if token is None:
        proc.kill()
        raise RuntimeError("lumen --bidi-port did not print [bidi] token")
    threading.Thread(target=lambda: collections.deque(proc.stderr, maxlen=0),
                     daemon=True).start()
    return proc, port, token


async def run_one(session, context, url: str, cap: float) -> dict:
    """Navigate and poll for testharness results; the arm's whole measurement."""
    from webdriver.bidi.error import BidiException, UnknownErrorException
    from webdriver.bidi.modules.script import ContextTarget

    started = time.time()
    try:
        await session.script.evaluate(expression=RESET_EXPRESSION,
                                      target=ContextTarget(context), await_promise=False)
    except BidiException:
        pass  # no JS runtime on the outgoing document — nothing to carry over
    try:
        await session.browsing_context.navigate(context=context, url=url, wait="complete")
    except BidiException as exc:
        return {"status": "NAV-ERROR", "message": str(exc), "seconds": time.time() - started}

    while True:
        try:
            value = await session.script.evaluate(expression=POLL_EXPRESSION,
                                                  target=ContextTarget(context),
                                                  await_promise=False)
        except UnknownErrorException as exc:
            # The JS runtime is installed off the UI thread, after `navigate`
            # answers — see executorlumen.py. Not ready is not an error.
            if "JS context not available" not in getattr(exc, "message", str(exc)):
                raise
        else:
            if value.get("type") == "string":
                outer = json.loads(value["value"])
                if outer["k"] == "r":
                    _url, code, message, _stack, subtests = json.loads(outer["v"])
                    return {"status": HARNESS_CODES.get(code, str(code)),
                            "message": message,
                            "subtests": len(subtests),
                            "passed": sum(1 for s in subtests if s[1] == SUBTEST_PASS),
                            "fixed": outer.get("fixed"),
                            "seconds": time.time() - started}
        if time.time() - started > cap:
            return {"status": "CAP", "seconds": time.time() - started}
        await asyncio.sleep(POLL_INTERVAL_S)


async def worker(binary: str, port_a: int, port_b: int, queue: list, lock,
                 cap: float, results: dict, progress) -> None:
    """One browser, both arms of every id it pulls off the shared queue."""
    from webdriver.bidi.client import BidiSession

    proc, bidi_port, token = launch(binary)
    session = BidiSession.bidi_only(f"ws://127.0.0.1:{bidi_port}",
                                    requested_capabilities={"alwaysMatch": {"token": token}})
    await session.start()
    try:
        tree = await session.browsing_context.get_tree()
        context = tree[0]["context"]
        while True:
            async with lock:
                if not queue:
                    return
                test_id = queue.pop()
            row = {}
            for arm, port in (("a", port_a), ("b", port_b)):
                url = f"http://127.0.0.1:{port}{test_id}"
                try:
                    row[arm] = await run_one(session, context, url, cap)
                except Exception as exc:  # noqa: BLE001 - one bad id must not end the run
                    row[arm] = {"status": "PROBE-ERROR", "message": str(exc)}
            results[test_id] = row
            progress(test_id, row)
    finally:
        try:
            await session.end()
        except Exception:  # noqa: BLE001 - the browser is about to be killed anyway
            pass
        proc.terminate()
        try:
            proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            proc.kill()


# --------------------------------------------------------------------------- #
# classification
# --------------------------------------------------------------------------- #

def classify(row: dict) -> tuple:
    """`(bucket, score_a, score_b)` for one id's two arms."""
    arm_a, arm_b = row.get("a") or {}, row.get("b") or {}
    if arm_a.get("status") in (None, "PROBE-ERROR", "NAV-ERROR"):
        return "probe-error", 0.0, 0.0
    if arm_b.get("status") in (None, "PROBE-ERROR", "NAV-ERROR"):
        return "probe-error", 0.0, 0.0
    score_a = score_of(arm_a["status"], arm_a.get("subtests", 0), arm_a.get("passed", 0))
    score_b = score_of(arm_b["status"], arm_b.get("subtests", 0), arm_b.get("passed", 0))
    a_timed_out = arm_a["status"] in ("TIMEOUT", "CAP")
    b_timed_out = arm_b["status"] in ("TIMEOUT", "CAP")
    if a_timed_out and not b_timed_out:
        return "recovered", score_a, score_b
    if score_b > score_a + 1e-9:
        return "improved", score_a, score_b
    if score_b < score_a - 1e-9:
        return "regressed", score_a, score_b
    if a_timed_out and b_timed_out:
        return "still-timeout", score_a, score_b
    return "unchanged", score_a, score_b


def project(rows: dict, population: int, corpus_ids: int) -> dict:
    """Sample -> population, in the units the headline is published in."""
    buckets = collections.Counter()
    delta = 0.0
    measured = 0
    for row in rows.values():
        bucket, score_a, score_b = classify(row)
        buckets[bucket] += 1
        if bucket != "probe-error":
            measured += 1
            delta += score_b - score_a
    mean = delta / measured if measured else 0.0
    projected = mean * population
    return {"buckets": dict(buckets), "measured": measured,
            "sample_delta": round(delta, 3), "mean_delta": round(mean, 4),
            "population": population,
            "projected_score": round(projected, 1),
            "projected_points": round(100.0 * projected / corpus_ids, 4) if corpus_ids else 0.0}


# --------------------------------------------------------------------------- #
# entry points
# --------------------------------------------------------------------------- #

def print_census(data: dict) -> None:
    """The population table — printed by every mode, browser or not."""
    print(f"`timeout: long` ids in the manifest: {data['long_declared']}")
    print(f"executed by this run:                {data['long_executed']}")
    for status, count in sorted(data["long_status"].items(), key=lambda kv: -kv[1]):
        print(f"    {status:<22} {count}")
    print("TIMEOUTs by which ceiling stopped them:")
    for mode, count in sorted(data["timeout_modes"].items(), key=lambda kv: -kv[1]):
        print(f"    {mode:<30} {count}")
    print(f"of the {len(data['fast'])} cut off at 10 s, probeable here: {len(data['probeable'])}")
    for reason, count in sorted(data["unservable"].items(), key=lambda kv: -kv[1]):
        print(f"    not probeable: {reason:<45} {count}")
    print("of the probeable ones, what the source says stands in the way "
          "(tags overlap):")
    for tag, count in sorted(data["strata"].items(), key=lambda kv: -kv[1]):
        print(f"    {tag:<25} {count}")
    if data.get("missing_helpers"):
        print("unvendored helper scripts they load:")
        for src, count in sorted(data["missing_helpers"].items(), key=lambda kv: -kv[1]):
            print(f"    {src:<55} {count}")


def _selftest() -> int:
    """Pure-function checks — no browser, no server, no corpus."""
    failures = []

    def check(name, cond):
        if not cond:
            failures.append(name)

    check("score: subtest ratio", abs(score_of("TIMEOUT", 4, 1) - 0.25) < 1e-9)
    check("score: bare PASS", score_of("PASS", 0, 0) == 1.0)
    check("score: bare OK scores nothing", score_of("OK", 0, 0) == 0.0)

    page = '<meta name="timeout" content="long">\n<script src="/resources/testharness.js"></script>'
    injected = inject_shim(page)
    check("shim lands before the include",
          injected.index("__lumen_repair_applied") < injected.index("testharness.js"))
    check("shim keeps the meta", injected.index('name="timeout"') < injected.index("<script>"))
    check("no include, no shim", inject_shim("<p>hi</p>") == "<p>hi</p>")

    check("report placeholders substitute",
          "timeout_multiplier: 1" in ("setup({timeout_multiplier: %(timeout_multiplier)s})"
                                      % REPORT_ARGS))

    rows = {
        "/a": {"a": {"status": "TIMEOUT", "subtests": 2, "passed": 0},
               "b": {"status": "OK", "subtests": 2, "passed": 2}},
        "/b": {"a": {"status": "TIMEOUT", "subtests": 0, "passed": 0},
               "b": {"status": "CAP", "subtests": 0, "passed": 0}},
        "/c": {"a": {"status": "OK", "subtests": 2, "passed": 1},
               "b": {"status": "OK", "subtests": 2, "passed": 1}},
        "/d": {"a": {"status": "PROBE-ERROR"}, "b": {"status": "OK"}},
    }
    check("recovered", classify(rows["/a"])[0] == "recovered")
    check("still-timeout", classify(rows["/b"])[0] == "still-timeout")
    check("unchanged", classify(rows["/c"])[0] == "unchanged")
    check("probe-error excluded", classify(rows["/d"])[0] == "probe-error")

    proj = project(rows, population=300, corpus_ids=1000)
    check("projection divides by measured ids only", proj["measured"] == 3)
    check("projection scales the mean", abs(proj["projected_score"] - 100.0) < 0.05)
    check("projection in points", abs(proj["projected_points"] - 10.0) < 0.01)

    # A CAP in arm B is a timeout for classification but its score is still 0.
    check("cap scores zero", score_of("CAP", 0, 0) == 0.0)
    check("harness codes decode", HARNESS_CODES[2] == "TIMEOUT" and HARNESS_CODES[0] == "OK")
    check("blocker scan flags a missing helper",
          "missing-helper" in structural_blockers(
              "/encoding/legacy-mb-korean/euc-kr/euckr-decode-cseuckr.html?1-1000"))
    check("blocker scan flags an iframe",
          "iframe" in structural_blockers(
              "/encoding/legacy-mb-korean/euc-kr/euckr-decode-cseuckr.html?1-1000"))
    check("blocker scan on a missing file says so",
          structural_blockers("/nope/does-not-exist.html") == {"unreadable"})

    if failures:
        for name in failures:
            print(f"selftest FAILED: {name}", file=sys.stderr)
        return 1
    print(f"selftest OK ({18 - len(failures)} checks)")
    return 0


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--binary", default=os.path.join(
        REPO_ROOT, "target", os.environ.get("LUMEN_PROFILE", "dev-release"), "lumen"))
    parser.add_argument("--out-dir", default=os.path.join(REPO_ROOT, ".tmp", "wpt-corpus"),
                        help="the corpus run's report directory (arm A's verdicts come "
                             "from the manifest+reports, the arms themselves are re-run)")
    parser.add_argument("--manifest", default=corpus_stats.DEFAULT_MANIFEST)
    parser.add_argument("--sample", type=int, default=40)
    parser.add_argument("--seed", type=int, default=796)
    parser.add_argument("--jobs", type=int, default=3)
    parser.add_argument("--cap", type=float, default=90.0,
                        help="wall-clock ceiling per arm (arm B's own ceiling is 65 s)")
    parser.add_argument("--stratum", choices=("all", "unblocked"), default="all",
                        help="`unblocked` samples only ids whose source shows no "
                             "structural reason to hang — the stratum where a wrong "
                             "ceiling could actually be the binding constraint")
    parser.add_argument("--census", action="store_true", help="population only, no browser")
    parser.add_argument("--json", help="write the full per-id table here")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        return _selftest()

    with open(args.manifest, encoding="utf-8") as fh:
        manifest = json.load(fh)
    verdicts = load_verdicts(args.out_dir)
    data = census(manifest, verdicts)
    print_census(data)
    if args.census:
        if args.json:
            with open(args.json, "w", encoding="utf-8") as fh:
                json.dump(data, fh, indent=1)
        return 0

    if not os.path.isfile(args.binary):
        print(f"lumen binary not found: {args.binary}", file=sys.stderr)
        return 1

    population = data["unblocked"] if args.stratum == "unblocked" else data["probeable"]
    rng = random.Random(args.seed)
    sample = rng.sample(population, min(args.sample, len(population)))
    print(f"\nprobing {len(sample)} of {len(population)} ({args.stratum}) on {args.jobs} browsers "
          f"(arm A: as served, arm B: meta.content repaired)\n")

    server_a, port_a = start_server(repair=False)
    server_b, port_b = start_server(repair=True)
    results = {}
    done = [0]

    def progress(test_id, row):
        done[0] += 1
        bucket = classify(row)[0]
        arm_a, arm_b = row["a"], row["b"]
        print(f"  [{done[0]:>3}/{len(sample)}] {bucket:<13} "
              f"A={arm_a.get('status'):<12}{arm_a.get('seconds', 0):5.1f}s  "
              f"B={arm_b.get('status'):<12}{arm_b.get('seconds', 0):5.1f}s  "
              f"fixed={arm_b.get('fixed')}  {test_id}", flush=True)

    async def drive():
        lock = asyncio.Lock()
        queue = list(sample)
        await asyncio.gather(*[
            worker(args.binary, port_a, port_b, queue, lock, args.cap, results, progress)
            for _ in range(max(1, args.jobs))])

    started = time.time()
    try:
        asyncio.run(drive())
    finally:
        server_a.shutdown()
        server_b.shutdown()

    corpus_ids = sum(1 for t, _c, _i in corpus_stats.iter_ids(manifest)
                     if t not in corpus_stats.NON_AUTOMATABLE_TYPES)
    proj = project(results, len(population), corpus_ids)
    print(f"\n{len(results)} ids probed in {(time.time() - started) / 60:.1f} min")
    for bucket, count in sorted(proj["buckets"].items(), key=lambda kv: -kv[1]):
        print(f"    {bucket:<15} {count}")
    print(f"\nmean score delta per probed id: {proj['mean_delta']:+.4f}")
    print(f"projected over {proj['population']} ids of the {args.stratum} stratum: "
          f"{proj['projected_score']:+.1f} score points "
          f"= {proj['projected_points']:+.4f} pass-rate points of {corpus_ids} ids")

    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump({"census": data, "sample": sample, "results": results,
                       "projection": proj}, fh, indent=1)
        print(f"wrote {args.json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
