#!/usr/bin/env python3
"""WPT-RUN-5 slice 32: what does BUG-792 cost the number, as opposed to reach?

[BUG-792](../../bugs/BUG-792-OPEN.md) states its reach and states it correctly:
`wptserve` answers close-delimited over TLS and never sends `close_notify`, our
body reader throws away everything it read on that error, so **7 190 automatable
manifest ids (10.6 % of the corpus) carry no document at all** — 0 harness OK and
0 subtests out of 635 executed `.https.` tests in the WPT-RUN-5 Linux half.

Reach is not price. Slices 30 and 31 measured that difference twice and both
times the price was two orders of magnitude below the reach ([BUG-796](
../../bugs/BUG-796-OPEN.md): 10.1 % of the corpus blocked, +0.10 pass-rate points
once unblocked). An id that never gets its document costs the figure only what it
*would have scored* with the document, and nothing so far has asked those 7 190
ids that question — they have never once run with a body.

This audit asks it directly, per test, with an A/B on the same binary against two
private TLS servers that differ in exactly one byte-level detail:

* **arm A** — EOF-framed response (no `Content-Length`, `Connection: close`), the
  socket then closed with no TLS shutdown. That is `wptserve`'s framing, and what
  the corpus run gets on every `.https.` id today.
* **arm B** — the same bytes, same headers, same EOF framing, `close_notify` sent
  before the close.

Arm B is not "some other server": it is the same response, ended politely. Since
the whole content of the fix is "treat `UnexpectedEof` on EOF framing as the end
of the body", the bytes the engine holds in arm B are exactly the bytes a fixed
engine would hold in arm A. The delta between the arms, scored by the published
rule, is therefore the price of BUG-792 in pass-rate points.

The framing is checked, not assumed: `--check-framing` (on by default) serves one
marker page from both arms and refuses to run unless arm A loses it and arm B
lays it out. Without that, an arm A that quietly worked would report a null result
that reads as "BUG-792 is free".

What this deliberately does not do, and why:

* **It does not run `wptserve`.** The corpus run owns the pinned ports and a
  second runner would either fight it for them or inherit a dead run's
  substituted harness options through the `StaticHandler` freeze (`CLAUDE.md`).
  Pages are served privately, the way `missing_helper_audit.py` does — whose
  server, `.sub.` substitution and BiDi scoring loop this reuses.
* **It does not write into `tests/wpt/`.** Same reason as slice 31: the corpus
  run reads test files off the doc root per request, and changing the tree
  mid-run hands later shards a different corpus than earlier ones.
* **It scores only ids with a file on disk.** 4 556 of the 7 190 have one; the
  other 2 634 are `.any.js`/`.window.js` ids whose html is generated by
  `wptserve` at request time, and generating them here would measure our wrapper
  rather than the engine. They are blocked by BUG-792 just the same — the census
  names them in ids so the unmeasured part is stated rather than implied.

Usage (from repo root, venv per tests/wpt/README.md):

    <venv>/python tests/wpt/tls_eof_audit.py --census
    <venv>/python tests/wpt/tls_eof_audit.py --sample 60 --jobs 3 --json OUT
    <venv>/python tests/wpt/tls_eof_audit.py --selftest
"""

import argparse
import asyncio
import collections
import functools
import http.server
import json
import os
import random
import ssl
import subprocess
import sys
import threading
import time

REPO_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
WPT_ROOT = os.path.join(REPO_ROOT, "tests", "wpt")
sys.path[:0] = [REPO_ROOT, os.path.join(REPO_ROOT, "tools", "webdriver"),
                os.path.dirname(os.path.abspath(__file__))]

import corpus_stats  # noqa: E402
import missing_helper_audit as mha  # noqa: E402

#: The test CA `tests/wpt/certs/` — `wptserve`'s own, trusted by the browser only
#: through `LUMEN_EXTRA_CA_CERT`, never by the system store.
CERTS = os.path.join(WPT_ROOT, "certs")

#: Path the framing check serves from both arms. Not a file: it must exist in
#: whatever tree the audit is pointed at, and it must be trivial enough that
#: "did it lay out" has one answer.
PROBE_PATH = "/__lumen_tls_framing_probe__.html"

#: A width and height the default UA stylesheet cannot produce by accident, so
#: finding both in a layout dump proves the body arrived and was parsed. Same
#: trick as `verify_bug792_tls_eof_body.py`, which isolates the defect itself.
PROBE_PAGE = (b"<html><body><div style='width:333px;height:77px'></div>"
              b"</body></html>")

#: How an id is recognised as belonging to the https corpus. `wptserve` decides
#: this by filename, and so does the manifest — `.https.` anywhere in the path
#: makes the test load over TLS. This is the same rule BUG-792 counted its 7 190
#: with, kept identical on purpose: a different rule would produce a different
#: denominator and the two numbers would stop being comparable.
def is_https_id(test_id: str) -> bool:
    """True if `wptserve` would serve this id over TLS."""
    return ".https." in test_id.split("?")[0]


# --------------------------------------------------------------------------- #
# population
# --------------------------------------------------------------------------- #

def census(manifest: dict, verdicts: dict) -> dict:
    """The https population and what it scores today, before a browser starts."""
    by_type = collections.Counter()
    ids = []
    total_automatable = 0
    for test_type, _category, test_id in corpus_stats.iter_ids(manifest):
        if test_type in corpus_stats.NON_AUTOMATABLE_TYPES:
            continue
        total_automatable += 1
        if not is_https_id(test_id):
            continue
        by_type[test_type] += 1
        ids.append((test_type, test_id))

    executed = 0
    held = 0.0
    executed_status = collections.Counter()
    for _type, test_id in ids:
        verdict = verdicts.get(test_id)
        if not verdict:
            continue
        executed += 1
        executed_status[verdict["status"]] += 1
        held += mha.score_of(verdict["status"], verdict["subtests"], verdict["passed"])

    probeable, unservable = [], collections.Counter()
    for test_type, test_id in ids:
        if test_type != "testharness":
            unservable[f"not testharness ({test_type})"] += 1
            continue
        reason = mha.unservable_reason(test_id)
        if reason:
            unservable[reason] += 1
        else:
            probeable.append(test_id)

    return {
        "automatable_ids": total_automatable,
        "https_ids": len(ids),
        "https_by_type": dict(by_type),
        "https_executed": executed,
        "https_executed_status": dict(executed_status.most_common(8)),
        "https_score_held": round(held, 2),
        "probeable": sorted(probeable),
        "unservable": dict(unservable),
    }


# --------------------------------------------------------------------------- #
# the two arms
# --------------------------------------------------------------------------- #

class EofHandler(mha.ArmHandler):
    """Serves `tests/wpt/` close-delimited: no `Content-Length`, ever.

    `wptserve` frames a large share of its responses this way (RFC 7230 §3.3.3
    item 7) and the engine supports it — the defect is not the framing, it is
    what happens at the end of the connection, which the *server* decides (see
    `TlsServer.clean_shutdown`). Both arms answer identically down to the byte;
    keeping `Content-Length` off in both is what makes that true.
    """

    protocol_version = "HTTP/1.1"

    def do_GET(self):  # noqa: N802 - name fixed by BaseHTTPRequestHandler
        site_path = self.path.split("?")[0]
        if site_path == PROBE_PATH:
            self._respond(200, PROBE_PAGE, "text/html")
            return None
        rendered = self.render(site_path)
        if rendered is None:
            self._respond(404, b"not found\n", "text/plain")
            return None
        body, content_type = rendered
        self._respond(200, body, content_type)
        return None

    def _respond(self, code: int, body: bytes, content_type: str) -> None:
        """Status line, headers, body — close-delimited, connection then dies."""
        self.send_response(code)
        self.send_header("Content-Type", content_type)
        # `Connection: close` also sets `close_connection`, so the server reaches
        # `shutdown_request` after this response — which is where the arms differ.
        self.send_header("Connection", "close")
        self.end_headers()
        try:
            self.wfile.write(body)
        except OSError:
            pass  # the browser gave up on this subresource; not our verdict

    def setup(self) -> None:
        """Do the TLS handshake in this connection's own thread.

        `socketserver` calls `get_request` on the accept loop, so a handshake
        started there stalls every other connection behind it — and a browser
        that abandons a subresource mid-handshake is routine in this population.
        """
        self.connection = self.request
        try:
            self.connection.do_handshake()
        except OSError:
            pass  # `rfile.readline()` below then reads nothing and the thread ends
        super().setup()


class TlsServer(http.server.ThreadingHTTPServer):
    """Threading HTTPS server whose *shutdown* is the experimental variable.

    `clean_shutdown = False` (arm A) closes the socket with no TLS shutdown at
    all, which is what `wptserve` does and what `rustls` reports as
    `UnexpectedEof`; `True` (arm B) calls `unwrap()` first, which sends
    `close_notify`. Python's `ssl` never sends one on plain `close()`, so the
    default really is the abrupt case rather than a polite one by accident —
    `--check-framing` proves it against the engine rather than trusting this
    paragraph.
    """

    daemon_threads = True
    clean_shutdown = False

    def __init__(self, address, handler, context):
        """Bind `address`; `context` wraps every accepted connection."""
        self.ssl_context = context
        super().__init__(address, handler)

    def get_request(self):
        """Accept and wrap; the handshake itself is deferred to `setup`."""
        sock, addr = super().get_request()
        return self.ssl_context.wrap_socket(sock, server_side=True,
                                            do_handshake_on_connect=False), addr

    def shutdown_request(self, request):
        """End the TLS session politely or not at all — the arms' one difference."""
        if self.clean_shutdown:
            try:
                request = request.unwrap()   # sends close_notify
            except OSError:
                pass  # already gone; nothing to say goodbye to
        super().shutdown_request(request)


def start_tls_server(clean_shutdown: bool) -> tuple:
    """Serve `tests/wpt/` over TLS on a free port; returns (server, port)."""
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain(os.path.join(CERTS, "host-cert.pem"),
                            os.path.join(CERTS, "host-key.pem"))
    handler = type("_TlsArm", (EofHandler,), {"cache": None})
    handler_partial = functools.partial(handler, directory=WPT_ROOT)
    server = TlsServer(("127.0.0.1", 0), handler_partial, context)
    server.clean_shutdown = clean_shutdown
    handler.port = server.server_address[1]
    threading.Thread(target=server.serve_forever, daemon=True).start()
    return server, server.server_address[1]


def browser_env() -> dict:
    """This process's environment plus the test CA the arms present."""
    return dict(os.environ, LUMEN_EXTRA_CA_CERT=os.path.join(CERTS, "ca-cert.pem"))


def framing_ok(arm_a_laid_out: bool, arm_b_laid_out: bool) -> bool:
    """Is the A/B valid at all — did arm A reproduce BUG-792 and arm B escape it?

    Both other outcomes are disqualifying, not merely surprising: two laid-out
    arms mean the abrupt close is not reaching the engine (nothing to measure,
    and a zero delta would read as "BUG-792 is free"), two lost ones mean arm B
    is broken for a reason of its own.
    """
    return arm_b_laid_out and not arm_a_laid_out


def check_framing(binary: str, port_a: int, port_b: int, timeout: float = 120) -> dict:
    """Prove arm A reproduces BUG-792 and arm B does not, on this build.

    Runs the marker page through `--dump-layout` on both ports. A run where arm A
    quietly succeeded would measure nothing and report it as "BUG-792 is free",
    which is the one wrong answer this audit could produce, so it is a
    precondition rather than a diagnostic.
    """
    out = {}
    for arm, port in (("a", port_a), ("b", port_b)):
        url = f"https://127.0.0.1:{port}{PROBE_PATH}"
        proc = subprocess.run([binary, "--dump-layout", url], cwd=REPO_ROOT,
                              env=browser_env(), capture_output=True, text=True,
                              timeout=timeout, check=False)
        out[arm] = "333" in proc.stdout and "77" in proc.stdout
        out[f"{arm}_stderr"] = "\n".join(
            line.strip()[:160] for line in (proc.stderr or "").splitlines()
            if "error" in line.lower() or "ошибка" in line.lower())[:600]
    out["ok"] = framing_ok(out["a"], out["b"])
    return out


# --------------------------------------------------------------------------- #
# entry points
# --------------------------------------------------------------------------- #

def print_census(data: dict) -> None:
    """The population table — printed by every mode, browser or not."""
    print(f"automatable ids in the manifest:   {data['automatable_ids']}")
    print(f"served over https by wptserve:     {data['https_ids']} "
          f"({100.0 * data['https_ids'] / max(1, data['automatable_ids']):.1f} %)")
    for test_type, count in sorted(data["https_by_type"].items(), key=lambda kv: -kv[1]):
        print(f"    {test_type:<22} {count}")
    print(f"of them executed by this run:      {data['https_executed']}, "
          f"holding {data['https_score_held']} score points today")
    for status, count in sorted(data["https_executed_status"].items(), key=lambda kv: -kv[1]):
        print(f"    {status:<22} {count}")
    print(f"probeable by a private server:     {len(data['probeable'])}")
    for reason, count in sorted(data["unservable"].items(), key=lambda kv: -kv[1]):
        print(f"    not probeable: {reason:<48} {count}")


def _selftest() -> int:
    """Pure-function checks — no browser, no network, no corpus."""
    failures = []

    def check(name, cond):
        if not cond:
            failures.append(name)

    check("https by filename", is_https_id("/a/b.https.any.html"))
    check("https survives a query", is_https_id("/a/b.https.html?x=.plain."))
    check("query alone does not make a test https", not is_https_id("/a/b.html?y=.https."))
    check("plain id is not https", not is_https_id("/a/b.window.html"))

    # The scoring rule and the buckets are the published ones, borrowed whole
    # from slice 31 so the two slices' numbers are in the same unit.
    check("score: subtest ratio", abs(mha.score_of("TIMEOUT", 4, 1) - 0.25) < 1e-9)
    check("score: bare PASS", mha.score_of("PASS", 0, 0) == 1.0)
    check("not-replaced counts as dead", "NOT-REPLACED" in mha.DEAD_STATUSES)

    rows = {
        # The shape this audit expects on a blocked id: arm A never gets a
        # document, arm B runs the test.
        "/a": {"a": {"status": "NOT-REPLACED", "subtests": 0, "passed": 0},
               "b": {"status": "OK", "subtests": 4, "passed": 3}},
        # BUG-792 hides the document, not necessarily a passing test.
        "/b": {"a": {"status": "NOT-REPLACED", "subtests": 0, "passed": 0},
               "b": {"status": "OK", "subtests": 2, "passed": 0}},
        "/c": {"a": {"status": "NOT-REPLACED", "subtests": 0, "passed": 0},
               "b": {"status": "NOT-REPLACED", "subtests": 0, "passed": 0}},
    }
    check("revived", mha.classify(rows["/a"])[0] == "revived")
    check("revived onto zero is still revived", mha.classify(rows["/b"])[0] == "revived")
    check("dead in both arms", mha.classify(rows["/c"])[0] == "still-dead")

    proj = mha.project(rows, population=1000, corpus_ids=10000)
    check("projection divides by measured ids only", proj["measured"] == 3)
    check("projection scales the mean", abs(proj["projected_score"] - 250.0) < 0.5)
    check("projection in points", abs(proj["projected_points"] - 2.5) < 0.01)

    # A framing check that says nothing must not read as a pass: only "arm B laid
    # it out AND arm A did not" is the state in which the measurement is valid.
    for arm_a, arm_b, want in ((False, True, True), (True, True, False),
                               (False, False, False), (True, False, False)):
        check(f"framing verdict A={arm_a} B={arm_b}", framing_ok(arm_a, arm_b) is want)

    if failures:
        for name in failures:
            print(f"selftest FAILED: {name}", file=sys.stderr)
        return 1
    print("selftest OK (17 checks)")
    return 0


def main() -> int:
    """CLI entry point."""
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--binary", default=os.path.join(
        REPO_ROOT, "target", os.environ.get("LUMEN_PROFILE", "dev-release"), "lumen"))
    parser.add_argument("--out-dir", default=os.path.join(REPO_ROOT, ".tmp", "wpt-corpus"),
                        help="the corpus run's report directory (for what the https "
                             "ids score today; the arms themselves are re-run)")
    parser.add_argument("--manifest", default=corpus_stats.DEFAULT_MANIFEST)
    parser.add_argument("--sample", type=int, default=60)
    parser.add_argument("--seed", type=int, default=792)
    parser.add_argument("--jobs", type=int, default=3)
    parser.add_argument("--cap", type=float, default=30.0,
                        help="wall-clock ceiling per arm. A page that wedges the "
                             "browser answers nothing, in either arm, and costs this "
                             "twice; `testharness.js` itself gives up at 10 s (60 s "
                             "for `timeout: long`, and BUG-796 currently makes even "
                             "those 10 s), so 30 s is past the point where a live "
                             "page still has something to report")
    parser.add_argument("--stale-cap", type=float, default=6.0,
                        help="how long an arm may sit on the outgoing document "
                             "before the navigation counts as never landed; arm A "
                             "spends this on every id by construction, so it sets the "
                             "floor price of the whole run")
    parser.add_argument("--prefix", default="",
                        help="sample only ids under this path, and project over that "
                             "stratum's own size — the population is heavy-tailed "
                             "(slice 31)")
    parser.add_argument("--census", action="store_true", help="population only, no browser")
    parser.add_argument("--no-check-framing", action="store_true",
                        help="skip the precondition that arm A actually reproduces "
                             "BUG-792 on this build; only for debugging the harness")
    parser.add_argument("--json", help="write the full per-id table here")
    parser.add_argument("--selftest", action="store_true")
    args = parser.parse_args()

    if args.selftest:
        return _selftest()

    with open(args.manifest, encoding="utf-8") as fh:
        manifest = json.load(fh)
    verdicts = mha.load_verdicts(args.out_dir)
    data = census(manifest, verdicts)
    print_census(data)
    if args.census:
        if args.json:
            with open(args.json, "w", encoding="utf-8") as fh:
                json.dump(data, fh, indent=1)
        return 0

    if not os.path.isfile(args.binary):
        print(f"lumen binary not found: {args.binary}", file=sys.stderr)
        return 1

    population = data["probeable"]
    if args.prefix:
        population = [tid for tid in population if tid.startswith(args.prefix)]
        if not population:
            print(f"no probeable id under {args.prefix}", file=sys.stderr)
            return 1

    server_a, port_a = start_tls_server(clean_shutdown=False)
    server_b, port_b = start_tls_server(clean_shutdown=True)
    framing = None
    try:
        if not args.no_check_framing:
            framing = check_framing(args.binary, port_a, port_b)
            print(f"\nframing check: arm A (abrupt) "
                  f"{'LAID OUT' if framing['a'] else 'LOST'}, "
                  f"arm B (close_notify) {'LAID OUT' if framing['b'] else 'LOST'}")
            for arm in ("a", "b"):
                if framing[f"{arm}_stderr"]:
                    print(f"    arm {arm}: {framing[f'{arm}_stderr'].splitlines()[0]}")
            if not framing["ok"]:
                print("the arms do not differ the way BUG-792 says they should — "
                      "nothing measured here would mean what it says", file=sys.stderr)
                return 2

        rng = random.Random(args.seed)
        sample = rng.sample(population, min(args.sample, len(population)))
        print(f"\nprobing {len(sample)} of {len(population)} https ids on {args.jobs} "
              f"browsers (arm A: no close_notify, arm B: close_notify)\n")

        results = {}
        done = [0]

        def progress(test_id, row):
            done[0] += 1
            bucket = mha.classify(row)[0]
            arm_a, arm_b = row["a"], row["b"]
            print(f"  [{done[0]:>3}/{len(sample)}] {bucket:<11} "
                  f"A={arm_a.get('status'):<12}{arm_a.get('seconds', 0):5.1f}s "
                  f"{arm_a.get('passed', 0)}/{arm_a.get('subtests', 0)}  "
                  f"B={arm_b.get('status'):<12}{arm_b.get('seconds', 0):5.1f}s "
                  f"{arm_b.get('passed', 0)}/{arm_b.get('subtests', 0)}  {test_id}",
                  flush=True)

        mha.disable_ws_keepalive()
        env = browser_env()

        async def drive():
            lock = asyncio.Lock()
            queue = list(sample)
            await asyncio.gather(*[
                mha.worker(args.binary, port_a, port_b, queue, lock, args.cap,
                           results, progress, scheme="https", env=env,
                           stale_cap=args.stale_cap, order=("b", "a"))
                for _ in range(max(1, args.jobs))])

        started = time.time()
        asyncio.run(drive())
    finally:
        server_a.shutdown()
        server_b.shutdown()

    corpus_ids = data["automatable_ids"]
    proj = mha.project(results, len(population), corpus_ids)
    print(f"\n{len(results)} ids probed in {(time.time() - started) / 60:.1f} min")
    for bucket, count in sorted(proj["buckets"].items(), key=lambda kv: -kv[1]):
        print(f"    {bucket:<15} {count}")
    dead_a = sum(1 for row in results.values()
                 if (row.get("a") or {}).get("status") in mha.DEAD_STATUSES)
    print(f"\narm A produced no document on {dead_a} of {len(results)} ids "
          f"(BUG-792 says it should be all of them)")
    capped_b = sum(1 for row in results.values()
                   if (row.get("b") or {}).get("status") == "CAP")
    print(f"arm B hit the {args.cap:.0f}s cap on {capped_b} ids — a page that answers "
          f"nothing wedges both arms alike, so those are counted as no verdict, not as "
          f"a zero the fix would have to earn")
    print(f"subtests seen: arm A {proj['subtests_a']}, arm B {proj['subtests_b']}")
    print(f"\nmean score delta per probed id: {proj['mean_delta']:+.4f}")
    print(f"projected over {proj['population']} probeable https ids: "
          f"{proj['projected_score']:+.1f} score points "
          f"= {proj['projected_points']:+.4f} pass-rate points of {corpus_ids} ids")
    unmeasured = data["https_ids"] - len(data["probeable"])
    print(f"outside the probed stratum: {unmeasured} https ids "
          f"(generated by wptserve, reftest, testdriver) — blocked the same, unmeasured here")

    if args.json:
        with open(args.json, "w", encoding="utf-8") as fh:
            json.dump({"census": data, "framing": framing, "sample": sample,
                       "results": results, "projection": proj}, fh, indent=1)
        print(f"wrote {args.json}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
