#!/usr/bin/env python3
"""WPT-RUN-6 slice 57: three unclassified-list candidates read by hand out of
the 30-id residual (`.tmp/audit-s56-after.json`'s `residual_ids`, re-measured
after slice 56's BUG-971 fix):

    /css/css-text/letter-spacing/letter-spacing-trim-start-002.html
    /fetch/security/dangling-markup/media.html
    /html/semantics/scripting-1/the-script-element/execution-timing/023.html

Picked after grepping `bugs/*.md` and every `tests/wpt/verify_slice*_gaps.py`
for each of the 30 residual ids first (slice 56's own lesson): 21 of the 30
turned out already covered — five already-probed-clean ids from slices
30/34/36/52-55 (`console-log-large-array.any.html`, `elements-at-point.html`,
`report-blocked-frame.sub.html`, `report-only-frame.sub.html`,
`content-visibility-069.html`, `background-change-during-smooth-scroll.html`,
`iframe-marginwidth-marginheight.html`, `frameset-element-synthetic-
{error,}event.html`, `video_crash_empty_src.html`), two dead ends already
re-verified in slice 56 itself (`grid-change-intrinsic-size-with-auto-repeat-
tracks-001.html`, `computed-initial.html`), one probe-tool-gap precedent
(`redirect-sharedworker.html`, BUG-866) and two already explained by filed
bugs without an `_exact_id_marker` entry yet (`apply_the_modifiers.html` /
`steps_for_selecting_the_payment_handler.html` — BUG-646, Payment Request
unimplemented; `po-mark-measure.any.html` — BUG-648, synchronous
`PerformanceObserver` delivery; not touched here, a marker-only follow-up).
Four more are **probe-tool gaps** this script cannot measure at all —
`serve_wpt_like.py` is a bare `SimpleHTTPRequestHandler` with no CGI, no
`{{domains[..]}}`/`{{ports[..]}}` substitution and no `?pipe=` support
(`docs/probe-method.md`'s `redirect-sharedworker.html` gotcha, generalized
here): `network-efficiency-guardrails-json.tentative.html` needs a real
`Document-Policy` response header (from its sibling `.headers` file, not
served) plus `?pipe=gzip`; `dictionary-decompression.tentative.https.h2.html`
needs a real h2/https origin; `orb/tentative/status.sub.html` needs both
`{{domains[www1]}}:{{ports[http][0]}}` substitution and `?pipe=status(301)|
header(...)`; `cors-expose-star.sub.any.html` is a `.any.js` test — its
`.any.html` wrapper is generated by wptserve's `.any.js` handler at request
time and does not exist as a file on disk, so this static server 404s it.
None of the four get a classifier entry from this slice; new gotcha recorded
in `docs/probe-method.md`. `MediaRecorder-destroy-script-execution.html` was
read but not probed: workspace-wide `grep -rn captureStream crates/` is
empty, so the support iframe's `createVideoStream` (canvas-backed fake
track, `mediacapture-record/utils/sources.js`) is a live candidate for a
TypeError-before-recorder-exists gap, but the test also layers named-window
frame access (`subFrameStart.window`, BUG-480 territory) and a cross-frame
`DOMException` constructor comparison (`testWindow.DOMException`, likely
another instance of the realm-identity gap already tracked by several open
frame-bridge bugs) on top — multiple already-known mechanisms stacked, not
a clean single root cause worth this slice's budget. Left in the residual
for a future slice with a narrower iframe-only repro.

Same evidence channel as slices 52-56: serve the real, unmodified files
through `serve_wpt_like.py` (the same substituted `testharnessreport.js` a
real corpus run uses) and read the `add_completion_callback` marker it
injects, plus any `[JS error]`/`script error:` line on stderr.

## Results (2026-09-04, dev-release, Linux, `main` = `ccdc0a6b5`)

One real TIMEOUT reclassified, no new bug (attributed to an already-filed
one):

- `execution-timing/023.html` — `harness-complete status=2 tests=1  scheduler:
  DOM added script, even later .src :2` (TIMEOUT). Same mechanism as
  [BUG-968](../../bugs/BUG-968-OPEN.md) (slice 55's `change-src-attr-prepare-
  a-script.html`), from the other direction: this page appends a `<script>`
  with no `src`/no body at all (`testlib.addScript('', {}, ...)`), so its
  connection-time "prepare a script" is a one-shot no-op, then sets `.src`
  for the first time afterwards and awaits `.onload` — which never fires,
  because nothing re-enters `_lumen_script_prepare` after the connection-time
  call regardless of what that call's `src` was. **Corrects BUG-968's own
  §Масштаб**, which had claimed this "no src → first src" shape was already
  covered by the connection-time trigger; it is not — `_lumen_resource_pending`
  is a strict one-shot gate, so this is the same defect, not a narrower one.
  Classified via `_exact_id_marker` in `timeout_audit.py` (existing marker
  `script-src-mutation-not-prepared`, id list extended, not a new mechanism).

Two real FAILs with no hang (no bug filed — WPT-RUN-6 is about TIMEOUTs, and
both FAIL promptly):

- `letter-spacing-trim-start-002.html` — `harness-complete status=0 tests=2
  ...:0|...:1` (1/2 subtests FAIL). `t.style.width = "max-content"` after
  `letter-spacing: 2ch` should shrink the box back to its natural
  (trim-adjusted) width; it doesn't. A real `letter-spacing`/`max-content`
  interaction gap, but not a hang; stays unclassified without a marker.
- `dangling-markup/media.html` — `harness-complete status=0 tests=4
  ...:1|...:0|...:1|...:0` (2/4 subtests FAIL: "should load audio"/"should
  load video"). Both "should load" subtests FAIL (real `/media/*.mp3`/`*.mp4`
  files never reach `canplay` — a separate, unmeasured media-playback gap),
  while both "should not load with dangling markup in URL" subtests PASS —
  consistent with either correct dangling-markup rejection or with media
  loading being broken regardless of URL shape; this probe cannot distinguish
  the two without a `canplay`-reaching baseline, and doesn't try to. No hang
  either way; stays unclassified without a marker.

Four ids read but not run — probe-tool gaps this script cannot measure at
all (see docstring above and `docs/probe-method.md`'s generalized
`serve_wpt_like.py` gotcha): `network-efficiency-guardrails-json.tentative.
html`, `dictionary-decompression.tentative.https.h2.html`, `orb/tentative/
status.sub.html`, `cors-expose-star.sub.any.html`. One id read but not run —
too many already-known mechanisms stacked for a clean attribution this slice
(`MediaRecorder-destroy-script-execution.html`, see docstring above).

Net: 1 of 3 run candidates reclassified against the existing BUG-968 marker.
unclassified 30 → 29 (`.tmp/audit-s57-after.json`, re-verified against the
cached `.tmp/wpt-corpus` WPT-RUN-5 snapshot with `timeout_audit.py --out-dir
.tmp/wpt-corpus`).

Usage (from repo root):

    tests/wpt/.venv/bin/python tests/wpt/verify_slice57_gaps.py
        [--binary target/dev-release/lumen] [--seconds 15]

Exit code is 0 whatever the outcome -- this is a measurement, not a gate.
"""

import argparse
import os
import re
import subprocess
import sys
import time

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(os.path.dirname(HERE))
SERVE_SCRIPT = os.path.join(HERE, "serve_wpt_like.py")

IDS = [
    "/css/css-text/letter-spacing/letter-spacing-trim-start-002.html",
    "/fetch/security/dangling-markup/media.html",
    "/html/semantics/scripting-1/the-script-element/execution-timing/023.html",
]

_MARKER_RE = re.compile(r"PROBE ([^\n\r]+)")
_ERROR_RE = re.compile(
    r"((?:script|module) error: [^\n\r]+"
    r"|\[JS error\] [^\n\r]+"
    r"|\[unhandled-rejection\] [^\n\r]+)")


def _start_server():
    proc = subprocess.Popen(
        [sys.executable, SERVE_SCRIPT],
        stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
    port_line = proc.stdout.readline().strip()
    return proc, int(port_line)


def _free_port():
    import socket
    with socket.socket() as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def _run_one(binary, http_port, test_id, seconds):
    log_path = os.path.join(REPO, ".tmp", f"s57-{test_id.strip('/').replace('/', '_')}.log")
    os.makedirs(os.path.dirname(log_path), exist_ok=True)
    url = f"http://127.0.0.1:{http_port}{test_id}"
    with open(log_path, "w", encoding="utf-8") as log:
        proc = subprocess.Popen(
            [binary, "--mcp-live-port", str(_free_port()), url],
            stdout=subprocess.DEVNULL, stderr=log, text=True)
        try:
            time.sleep(seconds)
        finally:
            proc.terminate()
            try:
                proc.wait(timeout=10)
            except subprocess.TimeoutExpired:
                proc.kill()
    with open(log_path, encoding="utf-8", errors="replace") as log:
        text = log.read()
    markers = []
    seen = set()
    for marker in _MARKER_RE.findall(text):
        marker = marker.strip()
        if marker in seen:
            continue
        seen.add(marker)
        markers.append(marker)
    for err in dict.fromkeys(_ERROR_RE.findall(text)):
        markers.append(f"[engine] {err.strip()}")
    return markers, text


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--binary", default=os.path.join(REPO, "target", "dev-release", "lumen"))
    parser.add_argument("--seconds", type=float, default=15.0)
    parser.add_argument("--id", action="append", default=None,
                         help="restrict to one or more of the three ids (repeatable)")
    parser.add_argument("--dump", action="store_true", help="print the full captured stderr too")
    args = parser.parse_args()

    wanted = args.id or IDS
    server, http_port = _start_server()
    try:
        for test_id in wanted:
            print(f"== {test_id} ==")
            markers, text = _run_one(args.binary, http_port, test_id, args.seconds)
            if markers:
                for m in markers:
                    print(f"  {m}")
            else:
                print("  — no PROBE/error marker seen at all")
            if args.dump:
                print("  --- full stderr ---")
                for line in text.splitlines():
                    print(f"  | {line}")
            print()
    finally:
        server.terminate()
        try:
            server.wait(timeout=5)
        except subprocess.TimeoutExpired:
            server.kill()
    return 0


if __name__ == "__main__":
    sys.exit(main())
