//! `about:chrome-preview` — render-smoke for the CC track's engine-drawn
//! chrome (CC-1, docs/tasks/p1-css-chrome.md).
//!
//! Loads `assets/chrome/chrome.html` (generated by
//! `scripts/gen_chrome_assets.py` from the frozen design reference) as an
//! ordinary page through the ordinary `PageSource::Static` path — no chrome
//! wiring yet, this exists purely to compare the existing HTML/CSS/layout
//! pipeline's rendering against the reference. Always available (not gated
//! by `LUMEN_CSS_CHROME`, unlike the runtime chrome host added in CC-4).

/// Canonical `about:` URL for the chrome render-smoke page.
pub const URL: &str = "about:chrome-preview";

/// Generated chrome asset, embedded at compile time (same convention as the
/// bundled chrome fonts in `lumen_paint::chrome_fonts`) so the preview works
/// regardless of the process's current working directory.
pub const HTML: &str = include_str!("../../../assets/chrome/chrome.html");
