// @generated by scripts/gen_tokens.py from docs/design/lumen-v3_3.html
// — do not edit by hand. Regenerate: `python scripts/gen_tokens.py`.
//! Design-system v3.3 tokens (radii, spacing, sizes, surface colours, accents).
//!
//! Every colour, radius and spacing literal used by the browser chrome must
//! come from this module instead of being hardcoded at the call site — see
//! `docs/tasks/p1-design-v3.md` (DS-1) and rule 3 in its per-slice checklist.
//!
//! # Wiring status
//!
//! DS-1 only introduces the module; consumers land slice by slice (DS-2..DS-19)
//! as chrome code migrates off local hardcoded literals.
#![allow(dead_code)]

/// Corner radii (px). Design-system rule: no radius above `LG` (no pills).
pub mod radius {
    /// `--radius-sm` in the design-system prototype.
    pub const SM: f32 = 2.0;
    /// `--radius-md` in the design-system prototype.
    pub const MD: f32 = 4.0;
    /// `--radius-lg` in the design-system prototype.
    pub const LG: f32 = 6.0;
}

/// Spacing scale (px), 4px grid.
pub mod space {
    /// `--space-1` in the design-system prototype.
    pub const S1: f32 = 4.0;
    /// `--space-2` in the design-system prototype.
    pub const S2: f32 = 8.0;
    /// `--space-3` in the design-system prototype.
    pub const S3: f32 = 12.0;
    /// `--space-4` in the design-system prototype.
    pub const S4: f32 = 16.0;
    /// `--space-6` in the design-system prototype.
    pub const S6: f32 = 24.0;
}

/// Fixed chrome element sizes (px).
pub mod size {
    /// `--sidebar-w` in the design-system prototype.
    pub const SIDEBAR_W: f32 = 240.0;
    /// `--sidebar-w-collapsed` in the design-system prototype.
    pub const SIDEBAR_W_COLLAPSED: f32 = 48.0;
    /// `--tab-h` in the design-system prototype.
    pub const TAB_H: f32 = 28.0;
    /// `--toolbar-h` in the design-system prototype.
    pub const TOOLBAR_H: f32 = 36.0;
}

/// Status/badge colours (theme-independent).
pub mod badge {
    use lumen_layout::Color;

    /// `--green` in the design-system prototype.
    pub const GREEN: Color = Color { r: 31, g: 157, b: 85, a: 255 };
    /// `--blue-badge` in the design-system prototype.
    pub const BLUE: Color = Color { r: 11, g: 111, b: 224, a: 255 };
    /// `--red-badge` in the design-system prototype.
    pub const RED: Color = Color { r: 224, g: 52, b: 43, a: 255 };
    /// `--yellow` in the design-system prototype.
    pub const YELLOW: Color = Color { r: 216, g: 164, b: 0, a: 255 };
    /// `--orange` in the design-system prototype.
    pub const ORANGE: Color = Color { r: 240, g: 138, b: 46, a: 255 };
}

/// `body[data-theme="light"]` surface tokens.
pub mod light {
    use lumen_layout::Color;

    /// `--surface-0` in the design-system prototype.
    pub const SURFACE_0: Color = Color { r: 255, g: 255, b: 255, a: 255 };
    /// `--surface-1` in the design-system prototype.
    pub const SURFACE_1: Color = Color { r: 248, g: 249, b: 250, a: 255 };
    /// `--surface-2` in the design-system prototype.
    pub const SURFACE_2: Color = Color { r: 240, g: 242, b: 245, a: 255 };
    /// `--stroke` in the design-system prototype.
    pub const STROKE: Color = Color { r: 225, g: 228, b: 232, a: 255 };
    /// `--text-primary` in the design-system prototype.
    pub const TEXT_PRIMARY: Color = Color { r: 31, g: 35, b: 40, a: 255 };
    /// `--text-secondary` in the design-system prototype.
    pub const TEXT_SECONDARY: Color = Color { r: 101, g: 109, b: 118, a: 255 };
    /// `--overlay-bg` in the design-system prototype.
    pub const OVERLAY_BG: Color = Color { r: 31, g: 35, b: 40, a: 89 };
}

/// `body[data-theme="dark"]` surface tokens.
pub mod dark {
    use lumen_layout::Color;

    /// `--surface-0` in the design-system prototype.
    pub const SURFACE_0: Color = Color { r: 18, g: 18, b: 18, a: 255 };
    /// `--surface-1` in the design-system prototype.
    pub const SURFACE_1: Color = Color { r: 26, g: 26, b: 26, a: 255 };
    /// `--surface-2` in the design-system prototype.
    pub const SURFACE_2: Color = Color { r: 36, g: 36, b: 36, a: 255 };
    /// `--stroke` in the design-system prototype.
    pub const STROKE: Color = Color { r: 45, g: 45, b: 45, a: 255 };
    /// `--text-primary` in the design-system prototype.
    pub const TEXT_PRIMARY: Color = Color { r: 230, g: 230, b: 230, a: 255 };
    /// `--text-secondary` in the design-system prototype.
    pub const TEXT_SECONDARY: Color = Color { r: 139, g: 148, b: 158, a: 255 };
    /// `--overlay-bg` in the design-system prototype.
    pub const OVERLAY_BG: Color = Color { r: 0, g: 0, b: 0, a: 140 };
}

/// Per-profile accent colours (`--accent`) and their soft/alpha variant
/// (`--accent-soft`), keyed by `body[data-profile=*]` in the prototype.
pub mod profile {
    use lumen_layout::Color;

    /// `--accent` for `body[data-profile="personal"]`.
    pub const PERSONAL: Color = Color { r: 0, g: 102, b: 255, a: 255 };
    /// `--accent-soft` for `body[data-profile="personal"]`.
    pub const PERSONAL_SOFT: Color = Color { r: 0, g: 102, b: 255, a: 33 };
    /// `--accent` for `body[data-profile="work"]`.
    pub const WORK: Color = Color { r: 139, g: 92, b: 246, a: 255 };
    /// `--accent-soft` for `body[data-profile="work"]`.
    pub const WORK_SOFT: Color = Color { r: 139, g: 92, b: 246, a: 36 };
    /// `--accent` for `body[data-profile="anonymous"]`.
    pub const ANONYMOUS: Color = Color { r: 255, g: 59, b: 48, a: 255 };
    /// `--accent-soft` for `body[data-profile="anonymous"]`.
    pub const ANONYMOUS_SOFT: Color = Color { r: 255, g: 59, b: 48, a: 36 };
    /// `--accent` for `body[data-profile="guest"]`.
    pub const GUEST: Color = Color { r: 142, g: 142, b: 147, a: 255 };
    /// `--accent-soft` for `body[data-profile="guest"]`.
    pub const GUEST_SOFT: Color = Color { r: 142, g: 142, b: 147, a: 36 };
}
