#!/usr/bin/env python3
"""Generate assets/chrome/chrome.html from the frozen design reference.

Strips everything the CC track's "Not the product" list excludes from the
engine-rendered chrome (docs/tasks/p1-css-chrome.md §2): the demo control
bar (7 layout variants + drag), the info panel, the `[data-tip]` developer
tooltip layer, the QA/tester panel, and the Google Fonts `<link>`s (Inter
and JetBrains Mono are already bundled in assets/fonts/, DS-4). The
`<script>` block is also removed — all ~40 interactions move to Rust in
later CC slices (CC-5/CC-6/CC-7).

The reference itself (docs/design/lumen-v3_3.html) is the frozen source of
truth and is never edited here; a design change means a new version of the
reference, then a re-run of this script.

Usage:
    python scripts/gen_chrome_assets.py          # (re)write assets/chrome/chrome.html
    python scripts/gen_chrome_assets.py --check  # exit 1 if the asset would change (drift check)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
SOURCE = ROOT / "docs" / "design" / "lumen-v3_3.html"
OUTPUT = ROOT / "assets" / "chrome" / "chrome.html"

GENERATED_HEADER = (
    "<!--\n"
    "  AUTO-GENERATED by scripts/gen_chrome_assets.py from docs/design/lumen-v3_3.html.\n"
    "  Do not hand-edit: a rendering mismatch vs. this file is an engine bug (BUG-NNN),\n"
    "  not something to patch here. To change the design, edit the reference and re-run\n"
    "  the generator (see docs/tasks/p1-css-chrome.md rule 4).\n"
    "-->\n"
)


class GenError(RuntimeError):
    """Raised when the source no longer matches an expected marker/structure."""


def _strip_between(text: str, start_pat: str, end_pat: str, *, label: str) -> str:
    """Remove text from the start of `start_pat` up to (not including) `end_pat`."""
    m_start = re.search(start_pat, text)
    if not m_start:
        raise GenError(f"{label}: start marker not found")
    m_end = re.search(end_pat, text[m_start.end() :])
    if not m_end:
        raise GenError(f"{label}: end marker not found")
    end = m_start.end() + m_end.start()
    return text[: m_start.start()] + text[end:]


def _strip_balanced_element(text: str, open_pat: str, tag: str, *, label: str) -> str:
    """Remove a whole `<tag ...> ... </tag>` element, tracking nested same-tag depth."""
    m_open = re.search(open_pat, text)
    if not m_open:
        raise GenError(f"{label}: opening tag not found")
    start = m_open.start()
    gt = text.index(">", m_open.end())
    pos = gt + 1
    open_re = re.compile(r"<" + tag + r"(?=[\s>])")
    close_re = re.compile(r"</" + tag + r">")
    depth = 1
    while depth > 0:
        m_open_next = open_re.search(text, pos)
        m_close = close_re.search(text, pos)
        if not m_close:
            raise GenError(f"{label}: unbalanced <{tag}> — no matching close")
        if m_open_next and m_open_next.start() < m_close.start():
            depth += 1
            pos = m_open_next.end()
        else:
            depth -= 1
            pos = m_close.end()
    return text[:start] + text[pos:]


def strip_google_fonts(html: str) -> str:
    html = re.sub(r'\n<link rel="preconnect"[^>]*>', "", html)
    html = re.sub(r'\n<link href="https://fonts\.googleapis\.com[^>]*>', "", html)
    return html


def strip_demo_css(html: str) -> str:
    return _strip_between(
        html,
        r"/\* =+\n\s*2\. ПАНЕЛЬ УПРАВЛЕНИЯ ДЕМО",
        r"/\* =+\n\s*3\. ОКНО LUMEN",
        label="demo CSS block",
    )


def strip_tooltip_css(html: str) -> str:
    return _strip_between(
        html,
        r"/\* -+ Тултипы \(документационный слой",
        r"/\* -+ Замок соединения",
        label="[data-tip] CSS block",
    )


def strip_qa_css(html: str) -> str:
    return _strip_between(
        html,
        r"/\* -+ QA / панель тестировщика -+ \*/\n\.qa-panel",
        r"</style>",
        label="QA CSS block",
    )


def strip_demo_bar_html(html: str) -> str:
    html = _strip_balanced_element(
        html, r'<div class="demo-bar"', "div", label="demo-bar element"
    )
    html = _strip_balanced_element(
        html, r'<div class="info-panel"', "div", label="info-panel element"
    )
    return html


def strip_qa_panel_html(html: str) -> str:
    html = re.sub(r'\n\s*<div class="qa-net-banner"[^>]*></div>', "", html)
    html = _strip_balanced_element(
        html, r'<aside class="qa-panel"', "aside", label="qa-panel element"
    )
    return html


def strip_script(html: str) -> str:
    return _strip_balanced_element(html, r"<script>", "script", label="script block")


def strip_tooltip_attrs(html: str) -> str:
    html = re.sub(r'\s+data-tip="[^"]*"', "", html)
    html = html.replace(' tip-right"', '"')
    html = html.replace(' class="tip-right"', "")
    return html


def collapse_blank_lines(html: str) -> str:
    return re.sub(r"\n{3,}", "\n\n", html)


def generate() -> str:
    html = SOURCE.read_text(encoding="utf-8")

    html = strip_google_fonts(html)
    html = strip_demo_css(html)
    html = strip_tooltip_css(html)
    html = strip_qa_css(html)
    html = strip_demo_bar_html(html)
    html = strip_qa_panel_html(html)
    html = strip_script(html)
    html = strip_tooltip_attrs(html)
    html = collapse_blank_lines(html)

    html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + GENERATED_HEADER, 1)
    return html


def main() -> int:
    check = "--check" in sys.argv
    generated = generate()

    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"DRIFT: {OUTPUT.relative_to(ROOT)} is stale — re-run without --check")
            return 1
        print(f"OK: {OUTPUT.relative_to(ROOT)} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
