#!/usr/bin/env python3
"""Generate crates/shell/src/theme_tokens.rs from docs/design/lumen-v3_3.html.

Source of truth: the CSS custom-property blocks in the design-system
prototype (`:root`, `body[data-theme="light"]`, `body[data-theme="dark"]`,
`body[data-profile=*]`). This script parses those four blocks and emits a
Rust module of typed constants so chrome code stops sprinkling magic colour
and radius literals — see docs/tasks/p1-design-v3.md (DS-1).

Modes:
    python scripts/gen_tokens.py           regenerate theme_tokens.rs
    python scripts/gen_tokens.py --check   compare against the committed file,
                                            exit 1 on drift (no write)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DESIGN_HTML = ROOT / "docs" / "design" / "lumen-v3_3.html"
OUTPUT = ROOT / "crates" / "shell" / "src" / "theme_tokens.rs"

# One CSS custom-property declaration, e.g. `--radius-sm:2px;` or
# `--overlay-bg: rgba(31,35,40,.35);`.
DECL = re.compile(r"--([\w-]+)\s*:\s*([^;]+);")

HEX6 = re.compile(r"^#([0-9A-Fa-f]{6})$")
RGBA = re.compile(
    r"^rgba\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*([\d.]+)\s*\)$"
)
PX = re.compile(r"^([\d.]+)px$")


def extract_block(src: str, selector: str) -> str:
    """Return the `{...}` body right after `selector` in `src`."""
    idx = src.index(selector)
    start = src.index("{", idx) + 1
    end = src.index("}", start)
    return src[start:end]


def parse_decls(block: str) -> dict:
    decls = {}
    for name, value in DECL.findall(block):
        decls[name] = value.strip()
    return decls


def color_to_rgba_u8(value: str) -> tuple:
    m = HEX6.match(value)
    if m:
        hexval = m.group(1)
        r, g, b = (int(hexval[i : i + 2], 16) for i in (0, 2, 4))
        return r, g, b, 255
    m = RGBA.match(value)
    if m:
        r, g, b = int(m.group(1)), int(m.group(2)), int(m.group(3))
        a = round(float(m.group(4)) * 255)
        return r, g, b, a
    raise ValueError(f"unrecognized colour value: {value!r}")


def px_to_f32(value: str) -> float:
    m = PX.match(value)
    if not m:
        raise ValueError(f"unrecognized px value: {value!r}")
    return float(m.group(1))


def rust_color(r: int, g: int, b: int, a: int) -> str:
    return f"Color {{ r: {r}, g: {g}, b: {b}, a: {a} }}"


def render(decls_root: dict, decls_light: dict, decls_dark: dict, decls_profiles: dict) -> str:
    out = []
    out.append("// @generated by scripts/gen_tokens.py from docs/design/lumen-v3_3.html")
    out.append("// — do not edit by hand. Regenerate: `python scripts/gen_tokens.py`.")
    out.append("//! Design-system v3.3 tokens (radii, spacing, sizes, surface colours, accents).")
    out.append("//!")
    out.append("//! Every colour, radius and spacing literal used by the browser chrome must")
    out.append("//! come from this module instead of being hardcoded at the call site — see")
    out.append("//! `docs/tasks/p1-design-v3.md` (DS-1) and rule 3 in its per-slice checklist.")
    out.append("//!")
    out.append("//! # Wiring status")
    out.append("//!")
    out.append("//! DS-1 only introduces the module; consumers land slice by slice (DS-2..DS-19)")
    out.append("//! as chrome code migrates off local hardcoded literals.")
    out.append("#![allow(dead_code)]")
    out.append("")
    out.append("/// Corner radii (px). Design-system rule: no radius above `LG` (no pills).")
    out.append("pub mod radius {")
    for name, const in (("radius-sm", "SM"), ("radius-md", "MD"), ("radius-lg", "LG")):
        out.append(f"    /// `--{name}` in the design-system prototype.")
        out.append(f"    pub const {const}: f32 = {px_to_f32(decls_root[name])};")
    out.append("}")
    out.append("")

    out.append("/// Spacing scale (px), 4px grid.")
    out.append("pub mod space {")
    for name, const in (
        ("space-1", "S1"),
        ("space-2", "S2"),
        ("space-3", "S3"),
        ("space-4", "S4"),
        ("space-6", "S6"),
    ):
        out.append(f"    /// `--{name}` in the design-system prototype.")
        out.append(f"    pub const {const}: f32 = {px_to_f32(decls_root[name])};")
    out.append("}")
    out.append("")

    out.append("/// Fixed chrome element sizes (px).")
    out.append("pub mod size {")
    for name, const in (
        ("sidebar-w", "SIDEBAR_W"),
        ("sidebar-w-collapsed", "SIDEBAR_W_COLLAPSED"),
        ("tab-h", "TAB_H"),
        ("toolbar-h", "TOOLBAR_H"),
    ):
        out.append(f"    /// `--{name}` in the design-system prototype.")
        out.append(f"    pub const {const}: f32 = {px_to_f32(decls_root[name])};")
    out.append("}")
    out.append("")

    out.append("/// Status/badge colours (theme-independent).")
    out.append("pub mod badge {")
    out.append("    use lumen_layout::Color;")
    out.append("")
    for name, const in (
        ("green", "GREEN"),
        ("blue-badge", "BLUE"),
        ("red-badge", "RED"),
        ("yellow", "YELLOW"),
        ("orange", "ORANGE"),
    ):
        r, g, b, a = color_to_rgba_u8(decls_root[name])
        out.append(f"    /// `--{name}` in the design-system prototype.")
        out.append(f"    pub const {const}: Color = {rust_color(r, g, b, a)};")
    out.append("}")
    out.append("")

    for mod_name, decls, doc in (
        ("light", decls_light, "`body[data-theme=\"light\"]` surface tokens."),
        ("dark", decls_dark, "`body[data-theme=\"dark\"]` surface tokens."),
    ):
        out.append(f"/// {doc}")
        out.append(f"pub mod {mod_name} {{")
        out.append("    use lumen_layout::Color;")
        out.append("")
        for name, const in (
            ("surface-0", "SURFACE_0"),
            ("surface-1", "SURFACE_1"),
            ("surface-2", "SURFACE_2"),
            ("stroke", "STROKE"),
            ("text-primary", "TEXT_PRIMARY"),
            ("text-secondary", "TEXT_SECONDARY"),
            ("overlay-bg", "OVERLAY_BG"),
        ):
            r, g, b, a = color_to_rgba_u8(decls[name])
            out.append(f"    /// `--{name}` in the design-system prototype.")
            out.append(f"    pub const {const}: Color = {rust_color(r, g, b, a)};")
        out.append("}")
        out.append("")

    out.append("/// Per-profile accent colours (`--accent`) and their soft/alpha variant")
    out.append("/// (`--accent-soft`), keyed by `body[data-profile=*]` in the prototype.")
    out.append("pub mod profile {")
    out.append("    use lumen_layout::Color;")
    out.append("")
    for profile, const in (
        ("personal", "PERSONAL"),
        ("work", "WORK"),
        ("anonymous", "ANONYMOUS"),
        ("guest", "GUEST"),
    ):
        accent = decls_profiles[(profile, "accent")]
        accent_soft = decls_profiles[(profile, "accent-soft")]
        r, g, b, a = color_to_rgba_u8(accent)
        rs, gs, bs, as_ = color_to_rgba_u8(accent_soft)
        out.append(f"    /// `--accent` for `body[data-profile=\"{profile}\"]`.")
        out.append(f"    pub const {const}: Color = {rust_color(r, g, b, a)};")
        out.append(f"    /// `--accent-soft` for `body[data-profile=\"{profile}\"]`.")
        out.append(f"    pub const {const}_SOFT: Color = {rust_color(rs, gs, bs, as_)};")
    out.append("}")
    out.append("")

    return "\n".join(out)


def generate() -> str:
    src = DESIGN_HTML.read_text(encoding="utf-8")

    decls_root = parse_decls(extract_block(src, ":root{"))
    decls_light = parse_decls(extract_block(src, 'body[data-theme="light"]{'))
    decls_dark = parse_decls(extract_block(src, 'body[data-theme="dark"]{'))

    decls_profiles = {}
    for profile in ("personal", "work", "anonymous", "guest"):
        block = parse_decls(extract_block(src, f'body[data-profile="{profile}"]{{'))
        for key in ("accent", "accent-soft"):
            decls_profiles[(profile, key)] = block[key]

    return render(decls_root, decls_light, decls_dark, decls_profiles)


def main() -> int:
    check = "--check" in sys.argv[1:]
    generated = generate()

    if check:
        if not OUTPUT.exists():
            print(f"дрейф: {OUTPUT} не существует")
            return 1
        current = OUTPUT.read_text(encoding="utf-8")
        if current != generated:
            print(f"дрейф: {OUTPUT} не совпадает со сгенерированным содержимым")
            return 1
        print(f"OK: {OUTPUT} соответствует эталону")
        return 0

    OUTPUT.write_text(generated, encoding="utf-8")
    print(f"сгенерирован: {OUTPUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
