#!/usr/bin/env python3
"""Generate assets/chrome/chrome.html from the frozen design reference.

Strips everything the CC track's "Not the product" list excludes from the
engine-rendered chrome (docs/tasks/p1-css-chrome.md §2): the demo control
bar (7 layout variants + drag), the info panel, the `[data-tip]` developer
tooltip layer, the QA/tester panel, and the Google Fonts `<link>`s (Inter
and JetBrains Mono are already bundled in assets/fonts/, DS-4). The
`<script>` block is also removed — all ~40 interactions move to Rust in
later CC slices (CC-5/CC-6/CC-7).

The reference itself (docs/design/lumen-v3_3.html) is the frozen source of
truth and is never edited here; a design change means a new version of the
reference, then a re-run of this script.

Usage:
    python scripts/gen_chrome_assets.py          # (re)write assets/chrome/chrome.html
    python scripts/gen_chrome_assets.py --check  # exit 1 if the asset would change (drift check)
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent.parent
SOURCE = ROOT / "docs" / "design" / "lumen-v3_3.html"
OUTPUT = ROOT / "assets" / "chrome" / "chrome.html"

GENERATED_HEADER = (
    "<!--\n"
    "  AUTO-GENERATED by scripts/gen_chrome_assets.py from docs/design/lumen-v3_3.html.\n"
    "  Do not hand-edit: a rendering mismatch vs. this file is an engine bug (BUG-NNN),\n"
    "  not something to patch here. To change the design, edit the reference and re-run\n"
    "  the generator (see docs/tasks/p1-css-chrome.md rule 4).\n"
    "-->\n"
)


class GenError(RuntimeError):
    """Raised when the source no longer matches an expected marker/structure."""


def _strip_between(text: str, start_pat: str, end_pat: str, *, label: str) -> str:
    """Remove text from the start of `start_pat` up to (not including) `end_pat`."""
    m_start = re.search(start_pat, text)
    if not m_start:
        raise GenError(f"{label}: start marker not found")
    m_end = re.search(end_pat, text[m_start.end() :])
    if not m_end:
        raise GenError(f"{label}: end marker not found")
    end = m_start.end() + m_end.start()
    return text[: m_start.start()] + text[end:]


def _strip_balanced_element(text: str, open_pat: str, tag: str, *, label: str) -> str:
    """Remove a whole `<tag ...> ... </tag>` element, tracking nested same-tag depth."""
    m_open = re.search(open_pat, text)
    if not m_open:
        raise GenError(f"{label}: opening tag not found")
    start = m_open.start()
    gt = text.index(">", m_open.end())
    pos = gt + 1
    open_re = re.compile(r"<" + tag + r"(?=[\s>])")
    close_re = re.compile(r"</" + tag + r">")
    depth = 1
    while depth > 0:
        m_open_next = open_re.search(text, pos)
        m_close = close_re.search(text, pos)
        if not m_close:
            raise GenError(f"{label}: unbalanced <{tag}> — no matching close")
        if m_open_next and m_open_next.start() < m_close.start():
            depth += 1
            pos = m_open_next.end()
        else:
            depth -= 1
            pos = m_close.end()
    return text[:start] + text[pos:]


def strip_google_fonts(html: str) -> str:
    html = re.sub(r'\n<link rel="preconnect"[^>]*>', "", html)
    html = re.sub(r'\n<link href="https://fonts\.googleapis\.com[^>]*>', "", html)
    return html


def strip_demo_css(html: str) -> str:
    return _strip_between(
        html,
        r"/\* =+\n\s*2\. ПАНЕЛЬ УПРАВЛЕНИЯ ДЕМО",
        r"/\* =+\n\s*3\. ОКНО LUMEN",
        label="demo CSS block",
    )


def strip_tooltip_css(html: str) -> str:
    return _strip_between(
        html,
        r"/\* -+ Тултипы \(документационный слой",
        r"/\* -+ Замок соединения",
        label="[data-tip] CSS block",
    )


def strip_qa_css(html: str) -> str:
    return _strip_between(
        html,
        r"/\* -+ QA / панель тестировщика -+ \*/\n\.qa-panel",
        r"</style>",
        label="QA CSS block",
    )


def strip_demo_bar_html(html: str) -> str:
    html = _strip_balanced_element(
        html, r'<div class="demo-bar"', "div", label="demo-bar element"
    )
    html = _strip_balanced_element(
        html, r'<div class="info-panel"', "div", label="info-panel element"
    )
    return html


def strip_qa_panel_html(html: str) -> str:
    html = re.sub(r'\n\s*<div class="qa-net-banner"[^>]*></div>', "", html)
    html = _strip_balanced_element(
        html, r'<aside class="qa-panel"', "aside", label="qa-panel element"
    )
    return html


def strip_script(html: str) -> str:
    return _strip_balanced_element(html, r"<script>", "script", label="script block")


def strip_tooltip_attrs(html: str) -> str:
    html = re.sub(r'\s+data-tip="[^"]*"', "", html)
    html = html.replace(' tip-right"', '"')
    html = html.replace(' class="tip-right"', "")
    return html


# CC-3 step 2 (docs/tasks/p1-css-chrome.md): the reference wires interactions
# through inline `onclick`/`onfocus`/`oninput` calling a `<script>` that this
# generator already strips (`strip_script`) — those handlers would otherwise
# be dead attributes referencing undefined functions. Each surviving
# `onclick` becomes a declarative `data-action="…"` (+ optional context
# attribute) that `lumen-chrome`'s build.rs turns into the `ChromeAction`
# enum; CC-5 will dispatch on it from hit-test instead of a JS engine.
#
# Keyed by the exact onclick body so a reference change that adds a new
# interaction — or changes an existing call's shape — fails generation
# loudly (GenError) instead of silently shipping a stale/dead attribute.
ONCLICK_EXACT_ACTIONS: dict[str, tuple[str, dict[str, str]]] = {
    "toggleFind()": ("toggle-find", {}),
    "toggleDevtools()": ("toggle-devtools", {}),
    "toggleDownloads()": ("toggle-downloads", {}),
    "toggleArchive()": ("toggle-archive", {}),
    "archiveRestore(this)": ("archive-restore", {}),
    "archiveDismiss(this)": ("archive-dismiss", {}),
    "toggleFocusTimer()": ("toggle-focus-timer", {}),
    "toggleFocus()": ("toggle-focus", {}),
    "toggleProfileMenu()": ("toggle-profile-menu", {}),
    "toggleSidebar()": ("toggle-sidebar", {}),
    "toggleShieldPopover(event)": ("toggle-shield-popover", {}),
    "toggleSwitch(this)": ("toggle-switch", {}),
    "closeRightSidebar()": ("close-right-sidebar", {}),
    "openAiSidebar()": ("open-ai-sidebar", {}),
    "openCertViewer(event)": ("open-cert-viewer", {}),
    "openPrintDialog()": ("open-print-dialog", {}),
    "openWebSidebar()": ("open-web-sidebar", {}),
    "selectTab(this)": ("select-tab", {}),
    "selectWs(this)": ("select-workspace", {}),
    "selectWsH(this)": ("select-workspace", {}),
    "fakeReload(this)": ("reload", {}),
    "showView('settings')": ("show-view", {"data-view": "settings"}),
    # Compound demo handler; `toggleQa()` targets the QA/tester panel already
    # removed by `strip_qa_panel_html` — only the view-switch survives.
    "showView('page');toggleQa()": ("show-view", {"data-view": "page"}),
    "ddGo('bookmarks')": ("show-view", {"data-view": "bookmarks"}),
    "ddGo('history')": ("show-view", {"data-view": "history"}),
    "closeModal('certOverlay')": ("close-modal", {}),
    "closeModal('printOverlay')": ("close-modal", {}),
    "if(event.target===this) closeModal('certOverlay')": ("close-modal", {}),
    "if(event.target===this) closeModal('printOverlay')": ("close-modal", {}),
    "if(event.target===this) closePalette()": ("close-palette", {}),
    "setDtTab(this,'elements')": ("set-devtools-tab", {"data-dt-tab": "elements"}),
    "setDtTab(this,'console')": ("set-devtools-tab", {"data-dt-tab": "console"}),
    "setDtTab(this,'network')": ("set-devtools-tab", {"data-dt-tab": "network"}),
    "setDtTab(this,'sources')": ("set-devtools-tab", {"data-dt-tab": "sources"}),
    "setRsTab(this,'ai')": ("set-sidebar-tab", {"data-rs-tab": "ai"}),
    "setRsTab(this,'web')": ("set-sidebar-tab", {"data-rs-tab": "web"}),
    "setPerm(this,'allow')": ("set-permission", {"data-perm": "allow"}),
    "setPerm(this,'deny')": ("set-permission", {"data-perm": "deny"}),
    "setSetSection(this,'appearance')": ("set-settings-section", {"data-section": "appearance"}),
    "setSetSection(this,'ext')": ("set-settings-section", {"data-section": "ext"}),
    "setSetSection(this,'general')": ("set-settings-section", {"data-section": "general"}),
    "setSetSection(this,'privacy')": ("set-settings-section", {"data-section": "privacy"}),
    "setSetSection(this,'qa')": ("set-settings-section", {"data-section": "qa"}),
    "setSetSection(this,'sync')": ("set-settings-section", {"data-section": "sync"}),
    "setProfile('personal')": ("set-profile", {"data-profile": "personal"}),
    "setProfile('work')": ("set-profile", {"data-profile": "work"}),
    "setProfile('anonymous')": ("set-profile", {"data-profile": "anonymous"}),
    "setProfile('guest')": ("set-profile", {"data-profile": "guest"}),
}

# A handful of onclick bodies carry no real signal (JS-only bubbling guard,
# or a demo `alert()` stub) — the true action is identified by the element's
# `class` instead. Checked before `ONCLICK_EXACT_ACTIONS`.
CLASS_ONCLICK_ACTIONS: dict[str, tuple[str, dict[str, str]]] = {
    "tab-close": ("close-tab", {}),  # onclick was only `event.stopPropagation()`
    "ws-add": ("add-workspace", {}),  # onclick was a demo `alert(...)` stub
    "hbar-add": ("new-tab", {}),
    "bm-card readlater": ("archive-card", {}),
}

_TAG_RE = re.compile(r"<([a-zA-Z][\w-]*)((?:\s+[^<>]*?)?)(/?)>")
_ATTR_RE = re.compile(r'([a-zA-Z_:][-\w:.]*)(?:\s*=\s*"([^"]*)")?')
_JS_HANDLER_ATTRS = ("onclick", "onfocus", "oninput")


def _classify_onclick(value: str, class_value: str) -> tuple[str, dict[str, str]]:
    if class_value in CLASS_ONCLICK_ACTIONS:
        return CLASS_ONCLICK_ACTIONS[class_value]
    if value in ONCLICK_EXACT_ACTIONS:
        return ONCLICK_EXACT_ACTIONS[value]
    if value.startswith("ddGo('page',"):
        return ("omni-go", {})
    raise GenError(
        f"add_data_actions: unmapped onclick={value!r} class={class_value!r} — "
        "reference gained a new interaction; add it to ONCLICK_EXACT_ACTIONS "
        "or CLASS_ONCLICK_ACTIONS"
    )


def add_data_actions(html: str) -> str:
    """Replace `onclick`/`onfocus`/`oninput` with declarative `data-action` (+ context).

    See `ONCLICK_EXACT_ACTIONS`/`CLASS_ONCLICK_ACTIONS` above.
    """

    def rewrite(m: re.Match[str]) -> str:
        tag, attr_str, selfclose = m.group(1), m.group(2), m.group(3)
        attrs = [(am.group(1), am.group(2)) for am in _ATTR_RE.finditer(attr_str) if am.group(1)]
        attr_map = dict(attrs)
        if not any(name in attr_map for name in _JS_HANDLER_ATTRS):
            return m.group(0)

        action = None
        extra: dict[str, str] = {}
        if "onclick" in attr_map:
            action, extra = _classify_onclick(attr_map["onclick"], attr_map.get("class", ""))
        # onfocus/oninput (address bar, command palette, find bar) carry no
        # data-action of their own — CC-7/CC-9 wire text editing separately
        # (hybrid `address_bar` model, brief risk #1). Just drop the dead attr.

        kept = [(n, v) for n, v in attrs if n not in _JS_HANDLER_ATTRS]
        if action is not None:
            kept.append(("data-action", action))
            kept.extend(extra.items())
        rebuilt = "".join(f' {n}="{v}"' if v is not None else f" {n}" for n, v in kept)
        return f"<{tag}{rebuilt}{selfclose}>"

    return _TAG_RE.sub(rewrite, html)


# CC-13 (docs/tasks/p1-css-chrome.md): declarative `role`/`aria-*` injection
# so `lumen_a11y::build_ax_tree` — the same builder that already reads ARIA
# off web pages — derives real chrome accessibility nodes (tab list, tabs,
# toolbar, address bar) straight from this markup, replacing the hand-rolled
# `lumen_a11y::chrome` synthetic snapshot (DS-17).
# Keyed off `id`/`data-testid`/`data-action` — all already stable, either
# native to the reference or synthesized by `add_data_actions` above (this
# function must run after it).
ARIA_ROLE_BY_ID: dict[str, dict[str, str]] = {
    "sbTabs": {"role": "tablist"},
    "hbarTabs": {"role": "tablist"},
    "omniInput": {"role": "combobox", "aria-autocomplete": "list"},
}
ARIA_ROLE_BY_TESTID: dict[str, dict[str, str]] = {
    "toolbar": {"role": "toolbar"},
}


def add_aria_roles(html: str) -> str:
    """Inject `role`/`aria-*` keyed by stable `id`/`data-testid`, plus
    `role="tab"` + `aria-selected` for every `data-action="select-tab"`
    element (vertical `.tab-row` and horizontal `.hbar-tab` mirrors alike).
    """

    def rewrite(m: re.Match[str]) -> str:
        tag, attr_str, selfclose = m.group(1), m.group(2), m.group(3)
        attrs = [(am.group(1), am.group(2)) for am in _ATTR_RE.finditer(attr_str) if am.group(1)]
        attr_map = dict(attrs)

        extra: dict[str, str] = {}
        extra.update(ARIA_ROLE_BY_ID.get(attr_map.get("id", ""), {}))
        extra.update(ARIA_ROLE_BY_TESTID.get(attr_map.get("data-testid", ""), {}))
        if attr_map.get("data-action") == "select-tab":
            extra["role"] = "tab"
            classes = (attr_map.get("class") or "").split()
            extra["aria-selected"] = "true" if "active" in classes else "false"

        if not extra:
            return m.group(0)

        kept = attrs + [(n, v) for n, v in extra.items() if n not in attr_map]
        rebuilt = "".join(f' {n}="{v}"' if v is not None else f" {n}" for n, v in kept)
        return f"<{tag}{rebuilt}{selfclose}>"

    return _TAG_RE.sub(rewrite, html)


# data-action (+ required extra attrs) → accessible label, for icon-only
# `<button>`s that carry no other visible text (checked by `add_aria_labels`
# below) — same set of controls DS-17's synthetic `ChromeButton` list named,
# now sourced from the real markup instead of hand-duplicated shell state.
# Buttons with their own visible text (e.g. the profile-menu toggle showing
# the current profile name) are left alone — the native text-derived name
# already carries more information than a static label would.
#
# Keyed by `data-action` alone, so a handful of actions reused on a
# structurally different icon-only button in another panel (e.g.
# "toggle-find"/"toggle-downloads"/"toggle-devtools" also dismiss their own
# panel via the same action) inherit the toolbar-toggle's label rather than
# a more precise "close panel" — an imprecise name beats the empty one these
# buttons had before ARIA injection existed, and a per-container label needs
# more context than this single-element regex pass has. Not chased further —
# out of this S-sized slice's DoD, same class of gap as CC-9/CC-10's
# per-download-card buttons.
ARIA_LABEL_RULES: list[tuple[str, dict[str, str], str]] = [
    ("reload", {}, "Обновить"),
    ("open-cert-viewer", {}, "Просмотр сертификата"),
    ("toggle-shield-popover", {}, "Экран приватности"),
    ("toggle-find", {}, "Найти на странице"),
    ("open-web-sidebar", {}, "Веб-сайдбар"),
    ("open-ai-sidebar", {}, "ИИ-сайдбар"),
    ("toggle-downloads", {}, "Загрузки"),
    ("toggle-archive", {}, "Архив вкладок"),
    ("toggle-devtools", {}, "DevTools"),
    ("show-view", {"data-view": "settings"}, "Настройки"),
    ("close-tab", {}, "Закрыть вкладку"),
    ("archive-restore", {}, "Восстановить вкладку"),
    ("archive-dismiss", {}, "Удалить из архива"),
]

_BUTTON_RE = re.compile(r"<button([^>]*)>((?:(?!</button>).)*?)</button>", re.DOTALL)
_STRIP_TAGS_RE = re.compile(r"<[^>]+>")


def add_aria_labels(html: str) -> str:
    """Give icon-only `<button>`s an `aria-label` per `ARIA_LABEL_RULES`.

    Runs over whole `<button>...</button>` elements (not just the opening
    tag, unlike `add_aria_roles`) because it needs to see whether the button
    already has visible text — icon-only buttons need a synthesized name,
    buttons with a text label (or an existing `aria-label`) don't.
    """

    def rewrite(m: re.Match[str]) -> str:
        attr_str, inner = m.group(1), m.group(2)
        attrs = [(am.group(1), am.group(2)) for am in _ATTR_RE.finditer(attr_str) if am.group(1)]
        attr_map = dict(attrs)
        action = attr_map.get("data-action")
        if action is None or "aria-label" in attr_map:
            return m.group(0)
        if _STRIP_TAGS_RE.sub("", inner).strip():
            return m.group(0)  # has its own visible text — don't shadow it

        for rule_action, extra, label in ARIA_LABEL_RULES:
            if rule_action != action:
                continue
            if any(attr_map.get(k) != v for k, v in extra.items()):
                continue
            rebuilt = "".join(f' {n}="{v}"' if v is not None else f" {n}" for n, v in attrs)
            return f"<button{rebuilt} aria-label=\"{label}\">{inner}</button>"
        return m.group(0)

    return _BUTTON_RE.sub(rewrite, html)


def collapse_blank_lines(html: str) -> str:
    return re.sub(r"\n{3,}", "\n\n", html)


def generate() -> str:
    html = SOURCE.read_text(encoding="utf-8")

    html = strip_google_fonts(html)
    html = strip_demo_css(html)
    html = strip_tooltip_css(html)
    html = strip_qa_css(html)
    html = strip_demo_bar_html(html)
    html = strip_qa_panel_html(html)
    html = strip_script(html)
    html = strip_tooltip_attrs(html)
    html = add_data_actions(html)
    html = add_aria_roles(html)
    html = add_aria_labels(html)
    html = collapse_blank_lines(html)

    html = html.replace("<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + GENERATED_HEADER, 1)
    return html


def main() -> int:
    check = "--check" in sys.argv
    generated = generate()

    if check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None
        if current != generated:
            print(f"DRIFT: {OUTPUT.relative_to(ROOT)} is stale — re-run without --check")
            return 1
        print(f"OK: {OUTPUT.relative_to(ROOT)} is up to date")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(generated, encoding="utf-8", newline="\n")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} ({len(generated)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
