#!/usr/bin/env python3
"""Generates crates/js/src/shim/svg_idl_table.js from the vendored WPT WebIDL
(tests/wpt/interfaces/SVG.idl + svg-animations.idl): the table the WebIDL-shape
pass in crates/js/src/svg.rs reads (BUG-1093). Run from the repo root:

    python scripts/gen_svg_idl_table.py

Format per interface: p = parent, c = constants, a = [name, type, flags]
(flags: 1 readonly, 2 [Reflect]), o = [name, required-arg-count, return type].
Mixins (SVGTests, SVGURIReference, ...) are merged into every includer;
mixins we do not model (event handlers, LinkStyle, ...) are dropped.
"""
import json
import re
import sys

ROOT = __file__.replace("\\", "/").rsplit("/scripts/", 1)[0]
SRC = ["tests/wpt/interfaces/SVG.idl", "tests/wpt/interfaces/svg-animations.idl"]
OUT = "crates/js/src/shim/svg_idl_table.js"

text = ""
for s in SRC:
    with open(f"{ROOT}/{s}", encoding="utf-8", newline="") as f:
        text += f.read().replace("\r\n", "\n") + "\n"
text = re.sub(r"//[^\n]*", "", text)

blocks = {}   # name -> dict(kind, parent, body)
includes = []  # (target, mixin)
for m in re.finditer(
    r"(?:\[[^\]]*\]\s*)?(partial\s+)?(interface\s+mixin|interface)\s+(\w+)\s*(?::\s*(\w+))?\s*\{(.*?)(?:\n\};|(?<=\{)\};)",
    text, re.S):
    partial, kind, name, parent, body = m.groups()
    b = blocks.setdefault(name, {"mixin": "mixin" in kind, "parent": None, "body": ""})
    if parent:
        b["parent"] = parent
    b["body"] += body + "\n"
for m in re.finditer(r"^(\w+)\s+includes\s+(\w+);", text, re.M):
    includes.append((m.group(1), m.group(2)))


def parse_body(body):
    consts, attrs, ops = {}, [], []
    for raw in body.split(";"):
        line = " ".join(raw.split())
        if not line:
            continue
        m = re.match(r"const \w+(?: \w+)* (\w+) = (-?\d+)$", line)
        if m:
            consts[m.group(1)] = int(m.group(2))
            continue
        ext = ""
        em = re.match(r"((?:\[[^\]]*\]\s*)+)(.*)", line)
        if em:
            ext, line = em.group(1), em.group(2)
        m = re.match(r"(?:(readonly) )?attribute (.+) (\w+)$", line)
        if m:
            flags = (1 if m.group(1) else 0) | (2 if "Reflect" in ext else 0)
            attrs.append([m.group(3), m.group(2).strip(), flags])
            continue
        if line.startswith("constructor"):
            continue
        line = re.sub(r"^(getter|setter|deleter) ", "", line)
        m = re.match(r"(.+?) (\w+)\((.*)\)$", line)
        if m:
            ret, name, args = m.groups()
            req = 0
            depth = 0
            parts, cur = [], ""
            for ch in args:
                if ch in "<(":
                    depth += 1
                if ch in ">)":
                    depth -= 1
                if ch == "," and depth == 0:
                    parts.append(cur)
                    cur = ""
                else:
                    cur += ch
            if cur.strip():
                parts.append(cur)
            for p in parts:
                if p.strip().startswith("optional"):
                    break
                req += 1
            ops.append([name, req, ret.strip()])
    return consts, attrs, ops


table = {}
for name, b in blocks.items():
    if b["mixin"] or not name.startswith(("SVG", "TimeEvent", "ShadowAnimation")):
        continue
    c, a, o = parse_body(b["body"])
    table[name] = {"p": b["parent"], "c": c, "a": a, "o": o}
for target, mixin in includes:
    if target in table and mixin in blocks and blocks[mixin]["mixin"] and mixin.startswith("SVG"):
        c, a, o = parse_body(blocks[mixin]["body"])
        table[target]["c"].update(c)
        table[target]["a"] += a
        table[target]["o"] += o

lines = ["// GENERATED by scripts/gen_svg_idl_table.py from tests/wpt/interfaces/SVG.idl +",
         "// svg-animations.idl — do not edit by hand. See crates/js/src/svg.rs.", "({"]
for name in sorted(table):
    lines.append(f"{name}:{json.dumps(table[name], separators=(',', ':'))},")
lines.append("})")
with open(f"{ROOT}/{OUT}", "w", encoding="utf-8", newline="\n") as f:
    f.write("\n".join(lines) + "\n")
print(len(table), "interfaces ->", OUT, file=sys.stderr)
