#!/usr/bin/env python3
"""Generate the blit-scroll acceptance fixtures (ADR-016 M3.2.1c-6).

Writes tall, high-frequency HTML pages under ``graphic_tests/blit-accept/`` that
`scripts/scroll_blit_accept.py` scrolls under ``LUMEN_SCROLL_BLIT`` on vs off and
diffs frame-for-frame. High vertical frequency (per-row color + black rule +
y-label) makes any band-blit misplacement of even one pixel show up as a large
diff; the ``position:fixed`` / ``sticky`` / transform-ancestor variants exercise
the overlay-replay paths (M3.2.1c-3…c-5).

Each page carries the same magenta 1px frame convention as the graphic_tests
suite (``body{background:#ff00ff}`` + ``.__f{margin:1px}``) so the acceptance
harness can calibrate its desktop-capture crop at scroll 0.

Run: ``python scripts/gen_blit_fixtures.py`` (regenerate after editing here).
"""

from __future__ import annotations

import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_DIR = os.path.join(REPO, "graphic_tests", "blit-accept")

# One template; per-fixture extra CSS / viewport-pinned overlay / row markup.
PAGE = """<!DOCTYPE html>
<!-- Blit-scroll acceptance fixture (ADR-016 M3.2.1c-6): generated by
     scripts/gen_blit_fixtures.py. Do not hand-edit. Tall, high-frequency
     content so any band-blit misplacement shows as a large flag-on-vs-flag-off
     pixel diff. Magenta 1px frame for scroll-0 crop calibration. -->
<html><head><meta charset="utf-8"><style>
  html,body{{margin:0;padding:0}}
  body{{background:#ff00ff}}
  .__f{{margin:1px;background:#fff}}
  .row{{height:48px;border-bottom:2px solid #000;font:20px/48px monospace;padding-left:8px;box-sizing:border-box}}
{extra_css}
</style></head><body>
{overlay}<div class="__f">
{rows}
</div></body></html>
"""

PALETTE = ["#ffcc00", "#00b3ff", "#ff5577", "#22cc88", "#aa66ff", "#ff8800"]


def rows(n: int = 60) -> str:
    """`n` vivid 50px-pitch rows with a black rule and a y-label each."""
    out = []
    for i in range(n):
        c = PALETTE[i % len(PALETTE)]
        out.append(
            f'<div class="row" style="background:{c}">row {i} &mdash; y={i * 50}px</div>'
        )
    return "\n".join(out)


# Fixture name -> template fields.
FIXTURES = {
    # Plain tall page: exercises the bare band blit + incremental expose path.
    "01-plain-tall.html": dict(extra_css="", overlay="", rows=rows()),
    # Top-level position:fixed header + corner badge: fixed-overlay replay.
    "02-fixed-header.html": dict(
        extra_css=(
            "  #hdr{position:fixed;top:0;left:0;right:0;height:40px;background:#1133aa;"
            "color:#fff;font:bold 22px/40px monospace;text-align:center;z-index:9}\n"
            "  #badge{position:fixed;bottom:12px;right:12px;width:80px;height:80px;"
            "background:#cc0033;border:3px solid #fff;border-radius:50%}"
        ),
        overlay='<div id="hdr">FIXED HEADER</div><div id="badge"></div>',
        rows=rows(),
    ),
    # position:sticky header: sticky-overlay replay.
    "03-sticky-header.html": dict(
        extra_css=(
            "  #sticky{position:sticky;top:0;height:40px;background:#0a7d2c;color:#fff;"
            "font:bold 22px/40px monospace;text-align:center;z-index:9}"
        ),
        overlay="",
        rows='<div id="sticky">STICKY HEADER</div>\n' + rows(),
    ),
    # position:fixed inside a transformed ancestor: the transform re-parents the
    # fixed box (spatial-ancestor replay, M3.2.1c-4/c-5).
    "04-transform-fixed.html": dict(
        extra_css=(
            "  #xform{transform:translateX(0);position:relative}\n"
            "  #pinned{position:fixed;top:60px;left:40px;width:160px;height:60px;"
            "background:#7700cc;color:#fff;font:bold 16px/60px monospace;text-align:center}"
        ),
        overlay="",
        rows='<div id="xform"><div id="pinned">XFORM-FIXED</div></div>\n' + rows(),
    ),
}


def main() -> None:
    """Write every fixture, creating the output directory if needed."""
    os.makedirs(OUT_DIR, exist_ok=True)
    for name, fields in FIXTURES.items():
        with open(os.path.join(OUT_DIR, name), "w", encoding="utf-8") as f:
            f.write(PAGE.format(**fields))
        print("wrote", os.path.join("graphic_tests", "blit-accept", name))


if __name__ == "__main__":
    main()
