//! Test 23-pseudo-elements.html — ::before / ::after generated content.
//!
//! Each `.box-*` host is 200x60; ::before/::after generate extra block boxes that
//! flow inside. We assert the hosts exist at 200x60 and that the generated boxes
//! show up in the flattened layout tree with their declared sizes (80x60 for the
//! narrow ::before, 200x40 for the box-both pseudo pair) — proving pseudo-element
//! boxes are actually created, not just the hosts.

use lumen_driver::{BrowserSession, InProcessSession};

fn navigate(session: &mut InProcessSession, file: &str) {
    let root = env!("CARGO_MANIFEST_DIR");
    let path = std::path::Path::new(root)
        .parent()
        .and_then(|p| p.parent())
        .expect("workspace root")
        .join(file);
    session
        .navigate(&format!("file://{}", path.display()))
        .expect("navigate");
}

fn approx(a: f32, b: f32) -> bool {
    (a - b).abs() < 1.0
}

#[test]
fn test_23_pseudo_elements() {
    let mut session = InProcessSession::new();
    navigate(&mut session, "graphic_tests/23-pseudo-elements.html");

    // Each host element is declared 200x60.
    for sel in [".box-before", ".box-after", ".box-both", ".box-narrow"] {
        let host = session
            .layout_box_by_selector(sel)
            .expect("query host")
            .unwrap_or_else(|| panic!("{sel} host not found"));
        assert!(
            approx(host.border_box.width, 200.0) && approx(host.border_box.height, 60.0),
            "{sel} should be 200x60, got {}x{}",
            host.border_box.width,
            host.border_box.height
        );
    }

    // Pseudo-elements generate real boxes. Scan the full layout tree for the
    // distinctive sizes only producible by the generated content:
    //  - 80x60  → .box-narrow::before
    //  - 200x40 → .box-both::before and ::after (two of them)
    let all = session.layout_snapshot().expect("layout snapshot");
    let narrow_pseudo = all
        .iter()
        .filter(|b| approx(b.border_box.width, 80.0) && approx(b.border_box.height, 60.0))
        .count();
    assert!(
        narrow_pseudo >= 1,
        "expected an 80x60 box generated by .box-narrow::before, found {narrow_pseudo}"
    );
    let both_pseudos = all
        .iter()
        .filter(|b| approx(b.border_box.width, 200.0) && approx(b.border_box.height, 40.0))
        .count();
    assert!(
        both_pseudos >= 2,
        "expected two 200x40 boxes from .box-both::before/::after, found {both_pseudos}"
    );
}
